"""Modul 4: Die Väter genommen, die Prediger geschickt, März bis Juni 1525.
Schreibt data/prediger.json.

Quelle, am Seitenbild gelesen: C. Höfler (Hg.), Denkwürdigkeiten der Charitas
Pirkheimer (Bamberg 1852), S. 33-58, 69-71, 84-96 in Auswahl (Internet Archive
11420769bsb; S. n = Blatt n+118). Höflers Klammerzusätze sind weggelassen.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "prediger.json"

OCULI = [
    dict(n=1, titel="Die Gesandten des Rates im Winterrefektorium", pg="Höfler S. 33–35", lang="fnhd",
         orig="Anno domini 1525 am suntag Oculi in der fasten was der 19 tag im Merzen nachmytag kom herr Cristof Koller vnd bernhart paumgartner, sagten, sy wern gesant von einem E. Rat von dem sy befelh hetten ein potschaft an den Convent zu werben, dy musten sy dem ganczen Convent ansagen, darvmb solt ich sy in das closter loßen [...] Also lyeß ich sye mit großen vorchten herein, berufft den Convent in den wynter Rebenter, huben dy 2 herren ein lange red an [...] als sich dann erfunden het in der cristenlichen disputacion dy iczunt etlich tag auf dem Rothauß gehalten worden in dem jr predicanten vnd hochgelert dy worheit des clarn gozwort also hell an tag hetten pracht, das dy ordens person dy do wern gewest selber hetten mußen bekennen das in gar vill stucken gejrrt wer worden [...] darvmb hetten sy vns verordent einen hochgelerten kostlichen prediger mit nomen herr poliander von wirtzpurg, der wurd als morgen montags anheben vns zu predigen das hell evangelium [...] Zudem andern wolt vns ein erbar Rot auch versehen mit peichtvettern vil paß dann wir pisher versehen wern gewest [...] schlugen vns fur 2 augustyner munch, einer hyeß karl, der ander dorfer, der 3 war ein leyenprister zu sant sebolt der hyeß herr feubelt, unter disen 3 solten wir einen nemen, welchen wir wollten [...] Zum 3. sprachen sy wer eines E. Rats ernstliche meynung, das wir die parfusser dy vns pisher regirt hetten in allen dingen mussig sollten gen vnd wir mit jn vnd sye mit vns nichs zu schaffen vnd zu schicken sollten haben.",
         en="Anno domini 1525, am Sonntag Oculi in der Fastenzeit, das war der 19. Tag im März, kamen nachmittags Herr Christoph Koler und Bernhard Baumgartner und sagten, sie seien von einem Ehrbaren Rat gesandt, von dem sie Befehl hätten, eine Botschaft an den Konvent auszurichten; die müssten sie dem ganzen Konvent ansagen, darum solle ich sie ins Kloster lassen [...] So ließ ich sie mit großer Furcht herein und rief den Konvent ins Winterrefektorium. Die zwei Herren begannen eine lange Rede [...] wie sich in der christlichen Disputation gezeigt habe, die jetzt einige Tage auf dem Rathaus gehalten worden sei, in der ihre Prediger und Hochgelehrten die Wahrheit des klaren Gotteswortes so hell an den Tag gebracht hätten, dass die Ordensleute, die dort gewesen seien, selbst hätten bekennen müssen, dass in gar vielen Stücken geirrt worden sei [...] Darum hätten sie uns einen hochgelehrten, kostbaren Prediger verordnet mit Namen Herr Poliander von Würzburg; der werde gleich morgen, Montag, anfangen, uns das helle Evangelium zu predigen [...] Zum anderen wolle uns ein Ehrbarer Rat auch mit Beichtvätern versehen, viel besser, als wir bisher versehen gewesen seien [...] Sie schlugen uns zwei Augustinermönche vor, der eine hieß Karl, der andere Dorfer; der dritte war ein Weltpriester zu Sankt Sebald, der hieß Herr Feubelt; unter diesen dreien sollten wir einen nehmen, welchen wir wollten [...] Zum Dritten, sagten sie, sei es die ernstliche Meinung eines Ehrbaren Rats, dass wir die Barfüßer, die uns bisher in allen Dingen regiert hätten, fortan meiden und wir mit ihnen und sie mit uns nichts mehr zu schaffen haben sollten.",
         note="Sonntag Oculi 1525 war der 19. März, wie Caritas schreibt. Das Religionsgespräch auf dem Rathaus hatte am 3. März begonnen (Modul ‚Verhört man doch einen Dieb‘). Drei Beschlüsse in einer Botschaft: ein Prediger des Rates (Johann Poliander; Caritas nennt ihn S. 62 einen ehemaligen Würzburger Chorherrn, der ‚auch ein Weib‘ habe), ein Beichtvater nach Wahl aus drei Kandidaten des Rates, und die Trennung vom Franziskanerorden. Ausgelassen sind lange Versicherungen der ‚väterlichen Gunst‘ des Rates; Caritas nennt sie ‚geschmierte Teidinge‘."),
    dict(n=2, titel="Die Antwort der Äbtissin: ‚vor Gott protestieren wir‘", pg="Höfler S. 35–36", lang="fnhd",
         orig="Auf diß antwurt ich an des conventes stat auf ein solche meynung vngefar wir wern einem E. R. dankpar aller gut gunstigkeit dy sye zu vns hetten [...] der peichtvetter aber halb, begern wir sunderlich von ganzem herczen, das vns ein E. R. vnser seelsorger nit nem, mit dem vnser closter ob 250 jarn woll versehen wer gewest [...] wolten der keinen annemen dy sye vns fur schlugen, hofften vnd getrawten ein E. R. wurd vns nit zwingen jn den dingen dy vnßer gewissen antreffen, so doch kein herschaft kein ehhalten zweng dem zu peichten den sy wolt wider jrn willen &c. Auf den 3 puncten, das sy vns wollten absundern von dem Regiment der parfusser gab ich dy antwurt, dy 2 orden wern von anfang jr styfftung also zusamengepunden [...] musten wir aber gewalt hyrinnen leyden so musten wirs Got befelhen, vor dem wir protestirten das wir solchen gewalt lyeden wider vnßer willen vnd das wir weder gunst noch willen geben in all artickel dy sy vns furgehalten hetten. — Diß was vngeferlich dy meinung meiner antwurt, do stund der ganz convent auf vnd gab mir gezeugtnus das es jr aller meinung wer wy ich geredt het.",
         en="Darauf antwortete ich an Stelle des Konvents ungefähr in dieser Meinung: Wir seien einem Ehrbaren Rat dankbar für alle Gunst, die er uns erweise [...] Was aber die Beichtväter angehe, begehrten wir besonders von ganzem Herzen, dass uns ein Ehrbarer Rat unsere Seelsorger nicht nehme, mit denen unser Kloster über 250 Jahre wohl versehen gewesen sei [...] Wir wollten keinen von denen annehmen, die sie uns vorschlügen, und hofften und vertrauten, ein Ehrbarer Rat werde uns nicht zwingen in den Dingen, die unser Gewissen angehen, da doch keine Herrschaft einen Dienstboten zwinge, gegen seinen Willen dem zu beichten, dem sie wolle usw. Auf den dritten Punkt, dass sie uns von der Leitung der Barfüßer trennen wollten, gab ich die Antwort, die zwei Orden seien seit dem Anfang ihrer Stiftung so miteinander verbunden [...] Müssten wir aber hierin Gewalt leiden, so müssten wir es Gott befehlen, vor dem wir protestierten, dass wir diese Gewalt gegen unseren Willen litten und dass wir zu keinem der Artikel, die sie uns vorgehalten hätten, Gunst oder Willen gäben. Das war ungefähr die Meinung meiner Antwort. Da stand der ganze Konvent auf und bezeugte mir, dass es ihrer aller Meinung sei, wie ich geredet hatte.",
         note="Die Äbtissin spricht ‚an Stelle des Konvents‘, und der Konvent bestätigt es stehend; das wiederholt sich bei jeder Verhandlung dieses Frühjahrs. Den Predigten widersetzt sie sich nicht (ausgelassene Stelle: Man habe ihnen das Evangelium auch bisher ‚klar gepredigt‘), wohl aber den Beichtvätern und der Trennung vom Orden. ‚Protestieren‘ ist hier ein Rechtsakt: Man erklärt vor Zeugen, dass man nur der Gewalt weicht, um seine Rechte nicht zu verlieren. Der Vergleich mit Dienstboten steht schon in den Briefen vom Advent (Modul ‚Die große Sündflut‘). ‚Ob 250 jarn‘: wieder eine andere Zahl."),
    dict(n=3, titel="‚Sollten wir Apostaten zu Seelsorgern nehmen?‘", pg="Höfler S. 36–37", lang="fnhd",
         orig="Do wärn die hern ernstlich, sagten auf den ersten puncten mit der predig wurd es ye keinen abgang haben [...] Den 2 punckten mit den peichtvettern sollten wir vns auch nit so gar schwer loßen sein [...] hetten wir aber ye einen scheuh vor den leyenpristern so mochten wir woll der 2 augustiner einen nennen, dy wern doch ordensperson vnd auch munch, sprach ich, will man vns munch geben, so loß man vns als mer vnßer munch, dy wir kennen [...] wir kennen dy munch auch woll dy ir vns genent habt, wissen woll, was sy fur einen loßen orden jzunt furn, sprachen sie, wir sollten vns dasselb auch nit loßen anfechten, sye werden aygentlich nit munch beleiben, sy wurden jr kutten hynlegen vnd ander stend an sich nemen. Sprach ich, Do wirt zumal nit auß, sollten wir erst apostaten zu selsorgern nemen, dy got meyneidig sind, was sollten wir vns denn gutes zu jn versehen, sy wurden vns nichcz lern denn was sye selber thun, als sy weiber nemen, maynten sye vielleicht wir sollten auch man nemen, do vns got vorbehut [...] Auf den 3 punckten der absunderung halb von dem orden begert ich man sollt vns anzaigen dy vrsach womit wir solchs verschuldt hetten [...] Auf deshalb antwurten sye, Ein E. R. hat kein wissen von keinem myßbrauch oder ergernus der von vns noch auch von den parfussern ye entstanden wer, sy westen nichs von vns dann alle zucht erberkait vnd gutten leymunt, sprach ich, darbey ließ man vns pillich beleiben.",
         en="Da wurden die Herren ernst und sagten, beim ersten Punkt, der Predigt, werde es ja keinen Abstrich geben [...] Auch den zweiten Punkt mit den Beichtvätern sollten wir uns nicht so schwer sein lassen [...] Hätten wir aber eine Scheu vor den Weltpriestern, so könnten wir ja einen der zwei Augustiner nennen, die seien doch Ordensleute und auch Mönche. Ich sprach: Will man uns Mönche geben, so lasse man uns ebenso gut unsere Mönche, die wir kennen [...] Wir kennen die Mönche, die Ihr uns genannt habt, auch wohl und wissen, was für einen losen Orden sie jetzt führen. Sie sprachen, das solle uns auch nicht anfechten, sie würden gewiss nicht Mönche bleiben, sondern ihre Kutten ablegen und einen anderen Stand annehmen. Ich sprach: Daraus wird ganz und gar nichts. Sollten wir gar Apostaten zu Seelsorgern nehmen, die Gott meineidig sind? Was sollten wir uns da Gutes von ihnen versehen? Sie würden uns nichts lehren, als was sie selbst tun, nämlich Weiber nehmen; meinten sie vielleicht, wir sollten auch Männer nehmen? Davor behüte uns Gott [...] Beim dritten Punkt, der Trennung vom Orden, verlangte ich, man solle uns die Ursache anzeigen, womit wir das verschuldet hätten [...] Darauf antworteten sie, ein Ehrbarer Rat wisse von keinem Missbrauch oder Ärgernis, das je von uns oder von den Barfüßern entstanden wäre; sie wüssten von uns nichts als alle Zucht, Ehrbarkeit und guten Ruf. Ich sprach: Dabei ließe man uns billigerweise bleiben.",
         note="Der Wortwechsel zeigt, wie offen die Gesandten waren: Die vorgeschlagenen Augustiner würden ohnehin bald heiraten. Das Nürnberger Augustinerkloster stand nach der neueren Literatur der Reformation früh offen. Die Gesandten bezeugen zugleich, dass dem Klarakloster nichts vorzuwerfen sei; ihre Begründung (ausgelassen): In anderen Orden gebe es solche Dinge, und was man an einem Ort tue, müsse man am anderen auch tun, sonst gebe es ‚Unfrieden und Nachrede‘."),
    dict(n=4, titel="Noch am selben Abend: die Väter gehen", pg="Höfler S. 37–38", lang="fnhd",
         orig="Do sye auß unserm closter komen gingen sye von stund an in das peichthauß, schuffen vnßern frumen alten peichtvater Erhart horolt vnd den prediger Nikolaum Liechtenstern von vns ab, sagten jn, eins E. R. meynung war das sye vns furpaß weder predigten noch peicht hörten noch nichs mit vns zu schaffen sollten haben, das theten dy lieben vetter vnd gingen von stund an die selbe nacht heym in ir closter. [...] Am Eritag darnach kam vnser peichtvater vnd prediger wider, hollten jrn werkzeug vnd was sye noch in dem peichthauß hetten, hyelten die predigt meß in der cappeln und renovirt das hochwürdig sacrament, das dester lenger also sten möcht, gingen darnach vor essens wider heym fur das mal sind sy kein tag mer heraufgangen [...] Wir sind ye syder der peicht, des hochwürdigen sacraments und aller cristenlichen sacrament peraubt, nit on kleine beschwerung unsers gewissens, auch in todts nötten, alsdann vnser liebe mitswester C. loffelholzin selige von grunt jrs herzens begert [...] Got im himel sey dieser geistlichen mengel geklagt, der erparm sich unser und schick schir ein guts mitel durch sein gruntloße parmherczigkeit.",
         en="Als sie aus unserem Kloster kamen, gingen sie sogleich ins Beichthaus, schafften unseren frommen alten Beichtvater Erhard Horolt und den Prediger Nikolaus Liechtenstern von uns ab und sagten ihnen, es sei die Meinung eines Ehrbaren Rats, dass sie uns fortan weder predigen noch Beichte hören noch irgendetwas mit uns zu schaffen haben sollten. Das taten die lieben Väter und gingen sofort, noch dieselbe Nacht, heim in ihr Kloster. [...] Am Dienstag danach kamen unser Beichtvater und Prediger wieder, holten ihr Werkzeug und was sie noch im Beichthaus hatten, hielten die Predigtmesse in der Kapelle und erneuerten das hochwürdige Sakrament, damit es desto länger so stehen könne; danach gingen sie vor dem Essen wieder heim. Seit diesem Mal sind sie keinen Tag mehr herausgekommen [...] Wir sind seitdem der Beichte, des hochwürdigen Sakraments und aller christlichen Sakramente beraubt, nicht ohne kleine Beschwerung unseres Gewissens, auch in Todesnöten, wie es unsere liebe Mitschwester C. Löffelholzin selig von Grund ihres Herzens begehrte [...] Dem Gott im Himmel sei dieser geistliche Mangel geklagt; der erbarme sich unser und schicke bald ein gutes Mittel durch seine grundlose Barmherzigkeit.",
         note="Das ‚Beichthaus‘ war der Wohnbau der Franziskaner beim Kloster. Die letzte Messe der Väter am Dienstag, 21. März: Sie ‚erneuern‘ die geweihten Hostien, damit sie länger aufbewahrt werden können, denn niemand würde neue weihen. Ausgelassen ist ein Satz, dass die Herren am selben Tag auch das Katharinenkloster der Dominikanerinnen ebenso behandelten, und einer über die Gerüchte, die Barfüßer gingen heimlich weiter ins Kloster. Die Löffelholzin starb nach Caritas' Bericht ohne Sakramente, weil sie sie aus der Hand eines Priesters ‚des Missglaubens halb‘ nicht nehmen wollte (ausgelassener Halbsatz)."),
]

PFLEGER = [
    dict(n=1, titel="Nützel predigt dem Konvent: die Bauern kommen", pg="Höfler S. 41–42", lang="fnhd",
         orig="Dißen seinem zusagen oder schreiben kom er an der pfincztag nacht, ließ wir jn allein jn das closter hereyn on gesellschaft wider unser gewonheit [...] also ging er mit großen frewden zu dem Convent und jubiliret hoch, das wir jnn zu unser rat beruft hetten [...] hub ein lange predigt an, jn der er die prediger hye auf das hoch lobet [...] und das sy bewerdt hatten, das durch die cristenlich freiheit nymant gebunden wer zu halten weder tagzeit, speiß noch kein menschliche sazung [...] es wer doch die gancz stat auf der newen maynung denn allein wir nit, wir wurden doch unßern orden und alte maynung nit künen erhalten, wo wir auf unsern synn wöllten verharren, so würden wir ursach geben zu großem plutvergießen und zu solchem aufrwre das die ganz stat dadurch zu verderbnus kumen möchten, denn er west das große versammlung der pawr vorhantten wern, und sammelten sich teglich mer und mer, die mit dem schwert dem goczwort und dem hellen evangelium wollten beysten und alle clöster abthun, darumb sollten wir unser pests bedenken, das wir nit mit unser sunderweiß ursach geben zu dem großen plutvergießen, das hernach wurd volgen.",
         en="Nach dieser seiner Zusage kam er am Donnerstagabend; wir ließen ihn allein ins Kloster herein, ohne Begleitung, gegen unsere Gewohnheit [...] So ging er mit großer Freude zum Konvent und jubelte laut, dass wir ihn zu unserem Rat gerufen hätten [...] Er fing eine lange Predigt an, in der er die Prediger hier aufs Höchste lobte [...] und dass sie bewiesen hätten, dass durch die christliche Freiheit niemand gebunden sei, Tagzeiten, Speisen oder irgendeine menschliche Satzung zu halten [...] Es sei doch die ganze Stadt der neuen Meinung, außer uns allein; wir würden unseren Orden und unsere alte Meinung doch nicht erhalten können. Wenn wir auf unserem Sinn beharren wollten, würden wir Ursache zu großem Blutvergießen und zu solchem Aufruhr geben, dass die ganze Stadt dadurch ins Verderben kommen könnte; denn er wisse, dass große Versammlungen der Bauern vorhanden seien, die sich täglich mehr und mehr sammelten und mit dem Schwert dem Gotteswort und dem hellen Evangelium beistehen und alle Klöster abtun wollten. Darum sollten wir unser Bestes bedenken, damit wir nicht mit unserer Sonderart Ursache zu dem großen Blutvergießen gäben, das danach folgen würde.",
         note="Der Pfleger kommt am Donnerstag, 23. März, auf die Bitte des Konvents, der ihn um Rat in der Bittschrift gefragt hatte. Im März 1525 sammelten sich in Franken und Schwaben die Bauernhaufen. Das Argument verschiebt die Verantwortung: Nicht wer Klöster stürmt, sondern wer an seinem Stand festhält, gibt ‚Ursache zum Blutvergießen‘."),
    dict(n=2, titel="‚Fragt alle Schwestern‘", pg="Höfler S. 42–44", lang="fnhd",
         orig="Sprach ich: W. lieber herr wir haben ewr red vernumen [...] dann es ye auf das höchst beschwerlich ist, das man uns mit gewalt will tringen von dem Regyment der frummen vetter [...] und uber das wil man uns überladen mit personen, die uns nit eben sindt, die ein leben furen wie jr wist, welchs wir in keinerley weiß werden annemen, allermeyst so wir merken daß diese ding alle allein darauf gespilt sind, das man uns durch solche mitel wil tringen zu dem newen gelauben, den wir in keinerley weiß werden annemen so lang pis er von ganczen gemaynen kristlichen kirchen wird angenumen [...] und was ich hie red, das red ich auß bevelh des ganzen Convents, Da stunden all swestern auf und gaben mir gezeugnuß. Sprach ich darnach weytter, auf das ich nit gezygen werdt, ich mach solche ding on mein swestern und sy mußen thun und reden was ich wöll, so will ich außtretten, so fragt all swestern in gemayn oder ein ytliche in sunderheit, wie es euch gefellt, und hört was einer ytlichen will in dißer sach ist. Aber er wollt mich nit außlassen tretten saget es wer auch on not die swester zu hörn, pat ich in zu 3 mal, das er die swester allein verhöret [...] sprach er hintten nach, ich weiß vor wol, was sy mir zu antwurt werden geben, er seh an jrn geberden wol, das jm keine wurd folgen.",
         en="Ich sprach: Weiser, lieber Herr, wir haben Eure Rede vernommen [...] Es ist uns aufs Höchste beschwerlich, dass man uns mit Gewalt von der Leitung der frommen Väter drängen will [...] und dass man uns darüber hinaus mit Personen überladen will, die uns nicht passen und die ein Leben führen, wie Ihr wisst. Das werden wir keinesfalls annehmen, zumal wir merken, dass diese Dinge alle allein darauf angelegt sind, uns durch solche Mittel zum neuen Glauben zu drängen, den wir keinesfalls annehmen werden, solange er nicht von der ganzen gemeinen christlichen Kirche angenommen wird [...] Und was ich hier rede, das rede ich im Auftrag des ganzen Konvents. Da standen alle Schwestern auf und bezeugten es mir. Ich sprach weiter: Damit man mir nicht nachsagt, ich mache solche Dinge ohne meine Schwestern und sie müssten tun und reden, was ich will, so will ich hinausgehen; dann fragt alle Schwestern gemeinsam oder jede einzeln, wie es Euch gefällt, und hört, was jeder Wille in dieser Sache ist. Aber er wollte mich nicht hinausgehen lassen und sagte, es sei auch unnötig, die Schwestern zu hören. Ich bat ihn dreimal, er möge die Schwestern allein anhören [...] Hinterher sprach er: Ich weiß vorher wohl, was sie mir zur Antwort geben werden; er sehe an ihren Gebärden wohl, dass ihm keine folgen werde.",
         note="Die Äbtissin bietet an, was der Konvent im Fall Tetzel für Margaretha verlangt hatte: eine Anhörung ohne die Oberin. Der Pfleger lehnt ab. Der Vorwurf, den er ihr wenige Minuten später im Chor macht ([5]), ist genau der, den sie hier entkräften wollte: dass sie allein den Konvent ‚widerspenstig‘ mache."),
    dict(n=3, titel="Die Bittschrift: im Leib verschlossen, im Gewissen gefangen?", pg="Höfler S. 47–48", lang="fnhd",
         orig="aber so der geist und die gewissen frey sollen sein, pitten wir E. F. W. als unser getrew herrn und veter so demutiglich, als leg wir vor ewren füßen umb der lieb willen des Herrn Jesu, der mit seinem kostbaren plutvergießen unser gewissen gerainigt hat, von den todten werken, das jr uns nit zwingen wölt in den dingen, die unser gewissen antreffent dann es ye ein cleglich erpermlich ding were, sollten wir zu leiblicher beschließung, in die wir uns willig ergeben haben, auch jn unser gewissen gefangen sein zu der zeit, so die evangelische Freiheit gepredigt wirdt, es ist bisher nit gewonheit gewesen, das man nymant genött und gemußigt hat einem zu peichten, der jm nit eben ist gewesen oder zu gelauben, was ein ander gewöllt hat [...] beger wir doch auf das hochst, das jr uns mit keinem andern beschwert, dann so man doch yez halt, das die orenpeicht on not sey, wöllen wir, so es nit anders sein mag, der auch wol entpern und unser manigfeltig sundt mit herzlichen myßfallen dem peichten, dem alle abgrunt der herczen offenbar sind.",
         en="Aber da der Geist und das Gewissen frei sein sollen, bitten wir Euer fürsichtige Weisheit als unsere getreuen Herren und Väter so demütig, als lägen wir vor Euren Füßen, um der Liebe des Herrn Jesus willen, der mit seinem kostbaren Blutvergießen unser Gewissen von den toten Werken gereinigt hat: Zwingt uns nicht in den Dingen, die unser Gewissen angehen. Denn es wäre ja ein klägliches, erbärmliches Ding, wenn wir zur leiblichen Verschließung, in die wir uns willig begeben haben, auch in unserem Gewissen gefangen sein sollten, zu der Zeit, da die evangelische Freiheit gepredigt wird. Es ist bisher nicht Gewohnheit gewesen, dass man jemanden genötigt und gezwungen hat, einem zu beichten, der ihm nicht recht war, oder zu glauben, was ein anderer wollte [...] So begehren wir doch aufs Höchste, dass Ihr uns mit keinem anderen beschwert. Denn da man jetzt doch hält, die Ohrenbeichte sei unnötig, so wollen wir, wenn es nicht anders sein kann, auf sie auch verzichten und unsere vielfältigen Sünden mit herzlichem Missfallen dem beichten, dem alle Abgründe der Herzen offenbar sind.",
         note="Die zweite Bittschrift des Konvents, Ende März 1525, von der Priorin vor dem Pfleger und dem ganzen Konvent verlesen. Ihr schärfster Gedanke: Die Klausur haben die Schwestern freiwillig gewählt; gefangen wären sie erst, wenn man ihnen jetzt, im Namen der evangelischen Freiheit, das Gewissen vorschreibt. Und die Pointe: Wenn die Reformatoren die Ohrenbeichte für unnötig halten, beichten die Schwestern eben Gott allein, dann brauchen sie auch keinen Beichtvater des Rates. Hebr 9,14."),
    dict(n=4, titel="‚Nur in diesem Stück wollt ihr lutherisch sein‘", pg="Höfler S. 50", lang="fnhd",
         orig="sprach ich unter andern dingen: gunt uns doch der freytag die die jr draußen habt, so jr nichcz von der peicht halt und nymer wollt peichten, so wollen wir hinnen auch nymer peichten, denn dem obersten prister; so wir denn nymer peichten wollen, so bedurff wir auch keins peichtvaters. Sprach er wie getz zu das jr in keinen dingen lutterisch wolt sein, denn jn dem stuck das jr nymer peichten wollt. sust wurden vil wort geredt, die nit alle mugen geschriben werden [...] Do er nun ausstund und aus dem Rebenter wolt gen, do lieffen die swester zu jm wider jr gewonheit knytten fur jn nyder und fyellen jm zu fussen un patten jn mit aller demutigkeit auf das allerhochst das er wollt helffen und unser beschützer und beschirmer wollt sein [...] aber es was jm übel vermaynet, stellet sich zornlich und hefftiglich, Ryß sich mit gewallt von den swestern.",
         en="Ich sprach unter anderem: Gönnt uns doch die Freiheit, die Ihr draußen habt: Da Ihr nichts von der Beichte haltet und nicht mehr beichten wollt, so wollen wir hier drinnen auch nicht mehr beichten, außer dem obersten Priester; wenn wir aber nicht mehr beichten wollen, so brauchen wir auch keinen Beichtvater. Er sprach: Wie geht das zu, dass ihr in keinen Dingen lutherisch sein wollt als in dem Stück, dass ihr nicht mehr beichten wollt? Sonst wurden viele Worte geredet, die nicht alle geschrieben werden können [...] Als er nun aufstand und aus dem Refektorium gehen wollte, liefen die Schwestern gegen ihre Gewohnheit zu ihm, knieten vor ihm nieder, fielen ihm zu Füßen und baten ihn in aller Demut aufs Allerhöchste, er wolle helfen und unser Beschützer und Beschirmer sein [...] Aber es war ihm übel gemeint; er stellte sich zornig und heftig und riss sich mit Gewalt von den Schwestern los.",
         note="Der Druck hat ‚gunt uns doch der freytag‘; gemeint ist offenbar ‚freyheit‘, und so ist übersetzt. Der ‚oberste Priester‘ ist Christus. Nützels Antwort ist der einzige Satz in diesem Teil, über den man lachen kann, und Caritas schreibt ihn ohne Kommentar auf. Der Kniefall der Schwestern ‚gegen ihre Gewohnheit‘ ist die Geste, die Nützel in seinem Brief zwei Tage später als ‚hohe Irrung‘ tadelt ([6])."),
    dict(n=5, titel="Eine Stunde im Chor: ‚dann hätten sie die ganze Landschaft‘", pg="Höfler S. 50–53", lang="fnhd",
         orig="Do er aus dem Rebenter kam, sagt er er het allein mit mir zu reden, furet mich jn den Chor, redet mer denn eine gancze stund alleyn mit mir unter vil liebkosen denn auch troenten worten [...] pat mich auf das hochst, ich sollt mich auf den rechten weg kern, daran thet ich jm und dem ganzen Rot den hochsten wollgefallen, denn sy hetten mich so lieb und wern mir so gunstig, wenn sy mich allein hetten auf jr meinung so hetten sy die ganze landschaft. [...] es wer aber das geschrey uber mich, das ich nit allein meinen Convent gegen den herrn verweyset, sundern auch alle umbligente frawencloster [...] Do er nun ein weil außgeredt, nam ich mir ein herctz und sagt im was mir zu mutt war, unter andern sprach ich: W. L. h. ich kann mich nit genug verwundern wy ir euch so heyß annempt um unßer sel seligkeit, so euch doch pflegsamts halben dy selsorg nit befolhen ist, dann jr seit allein pfleger uber die zeitlichen guter, so nempt ir euch an gewalts den ir nit habt [...] Ir begert an mich das ich dy swestern soll halten und weißen zu den dingen, dy wider mein gewissen sind, das wert ich nit thun durch keins menschen gunst oder forcht wegen, kenn auch meinen Convent so frumm und redlich, wenn ich schon nit wer, so werden sy sich mit nichte begeben in das wider jr gewissen ist. [...] Es haben mir auch meyn swestern unter augen verpotten, ich will zu nichten verwilligen, thu ichs aber, so wollten sy nit darein vergunstigen und mir nymer gehorsam sein. [...] Wir haben nach unser regel die Freyheit, das wir mügen erwelen zu einer Abtissin, wen wir wöllen, hat uns nymant darein zu sprechen [...] dann als wenig wir wissen wer euch eben in ewr Rot ist, als wenig kunt jr wissen wer uns duglich jn unser Closter.",
         en="Als er aus dem Refektorium kam, sagte er, er habe allein mit mir zu reden, führte mich in den Chor und redete mehr als eine ganze Stunde allein mit mir, mit vielen Liebkosungen und auch drohenden Worten [...] Er bat mich aufs Höchste, ich solle mich auf den rechten Weg bekehren; daran täte ich ihm und dem ganzen Rat das höchste Wohlgefallen, denn sie hätten mich so lieb und seien mir so gewogen; wenn sie mich allein auf ihrer Meinung hätten, so hätten sie die ganze Landschaft. [...] Es gehe aber das Geschrei über mich, dass ich nicht allein meinen Konvent gegen die Herren aufbringe, sondern auch alle umliegenden Frauenklöster [...] Als er eine Weile ausgeredet hatte, fasste ich mir ein Herz und sagte ihm, wie mir zumute war; unter anderem sprach ich: Weiser, lieber Herr, ich kann mich nicht genug wundern, wie Ihr Euch so heiß um unser Seelenheil annehmt, da Euch doch kraft Eures Pflegeramts die Seelsorge nicht befohlen ist; denn Ihr seid allein Pfleger über die zeitlichen Güter, und so nehmt Ihr Euch eine Gewalt an, die Ihr nicht habt [...] Ihr begehrt von mir, ich solle die Schwestern zu Dingen halten und anweisen, die gegen mein Gewissen sind; das werde ich um keines Menschen Gunst oder Furcht willen tun, und ich kenne auch meinen Konvent so fromm und redlich: Wenn ich auch nicht wäre, so werden sie sich keineswegs in das begeben, was gegen ihr Gewissen ist. [...] Es haben mir auch meine Schwestern ins Gesicht verboten, zu irgendetwas einzuwilligen; täte ich es, so würden sie nicht zustimmen und mir nicht mehr gehorsam sein. [...] Wir haben nach unserer Regel die Freiheit, zur Äbtissin zu wählen, wen wir wollen; da hat uns niemand hineinzureden [...] Denn so wenig wir wissen, wer Euch in Euren Rat passt, so wenig könnt Ihr wissen, wer uns in unser Kloster taugt.",
         note="Nützels Satz ‚wenn sie mich allein hätten, so hätten sie die ganze Landschaft‘ zeigt, wie man Caritas im Rat sah: als Haupt des Widerstands der Frauenklöster ringsum. Ihre Antwort trennt die Ämter: Der Pfleger verwaltet das Gut, die Seelsorge ist nicht sein Amt. Am Ende geht es um die Wahl der Äbtissin, die die Regel dem Konvent gibt; Caritas fürchtet, der Rat werde ihnen eines Tages eine Äbtissin setzen. Ausgelassen sind ein Wortwechsel über Visitation und Nützels Angebot, jeden Beichtvater zu holen, ‚nur keinen von der alten Sekte‘. Höfler setzt zu Nützels Drohung mit dem Blutvergießen eine Anmerkung: ‚Als ob sich die Bauern dadurch hätten abhalten laßen, zu morden und zu brennen‘ (S. 51); das ist das Urteil des Herausgebers von 1852, nicht der Quelle. Eine zweite Anmerkung Höflers wundert sich, dass der Pfleger Willibald Pirckheimer nicht erwähnt."),
    dict(n=6, titel="‚Ich spüre noch keinen Heiligen Geist‘", pg="Höfler S. 54–57", lang="fnhd",
         orig="Als wir nun pede aufstunden kom sein tochter Clara, nam die andern swestern, die veter im Rot hetten, mit jr, und fyellen jm zu fussen, paten jn auf das hochst, das er ir veter pet, das sis im Closter ließen. Aber er went sich unverwirßlich von jn, ging also mit großer schwermutigkeit und ernst auß dem closter, sprach, ich bin mit großen frewden hereingangen in hoffnung ich wurd meinen herrn eins E. R. ein gute potschaft bringen, so ist mir die genad nit geschaffen, waiß nit was ich zu antwurt soll geben, dann ich spür noch nit kein heiligen geist. Am nechsten tag darnach kom sein haußfraw mit großem zorn laß uns ein groß Capitel [...]\n\n[Aus Nützels Brief vom 25. März:] Warlich warlich sag ich euch, nit ich, sunder der herr, jr seit plint und durch plint pisher gefürt [...] Ich muß auß gottes willen bedranglich und noch deutscher reden, jr wollt dy sein dy plutvergyßen mordt und alles ungeluck verursachen wollen [...]",
         en="Als wir beide aufstanden, kam seine Tochter Clara, nahm die anderen Schwestern mit, die Väter im Rat hatten, und sie fielen ihm zu Füßen und baten ihn aufs Höchste, er möge ihre Väter bitten, sie im Kloster zu lassen. Aber er wandte sich unwillig von ihnen und ging mit großer Schwermut und Ernst aus dem Kloster und sprach: Ich bin mit großer Freude hereingegangen in der Hoffnung, ich würde meinen Herren eines Ehrbaren Rats eine gute Botschaft bringen; nun ist mir diese Gnade nicht beschieden, ich weiß nicht, was ich zur Antwort geben soll, denn ich spüre noch keinen Heiligen Geist. Am nächsten Tag darauf kam seine Hausfrau in großem Zorn und las uns ein großes Kapitel [...]\n\n[Aus Nützels Brief vom 25. März:] Wahrlich, wahrlich, sage ich euch, nicht ich, sondern der Herr: Ihr seid blind und bisher durch Blinde geführt [...] Ich muss nach Gottes Willen bedrängt und noch deutlicher reden: Ihr wollt die sein, die Blutvergießen, Mord und alles Unglück verursachen wollen [...]",
         note="Clara Nützel, die Tochter des Pflegers, kniet mit den anderen Ratstöchtern vor ihm; drei Monate später holten die Eltern sie heraus (Modul ‚Da stee ich‘). Nützels Brief vom Samstag vor Laetare, Mariä Verkündigung (25. März), ist im Ton höflich und in der Sache unversöhnlich: Er droht mit dem Beispiel des Schwäbischen Bundes und mit einem ‚Volk ohne Haupt‘, über 50.000 stark, zwei oder drei Tagesreisen von hier (ausgelassen). Die Rede seiner Frau, die ‚ein großes Kapitel las‘, ist nur in einem Satz überliefert."),
]

PREDIGER = [
    dict(n=1, titel="Die Marterwoche: alle Prediger der Stadt", pg="Höfler S. 69–71", lang="fnhd",
         orig="Also am pfincztag nach judica sollt der karteusser zum ersten predigen, do ward er krank. Am palmtag do predigt der prediger zu sant sebolt Dominicus, am montag und mitwoch der prediger zu sant lorenzen Osiander, am antlaßtag der wider zu sant gilgen, am karfreitag und ostertag der dominicus, an andern und 3 öftertag der osiander, am samstag der karteusser das erstmal. Am suntag quasimodo der dominicus das letztmal, also mußten wir dy ganze marterwochen all prediger hörn, das man vns newst mit gewalt bekert, das wir nymer weichen kundten. hatten warlich ein schwere marterwochen, groß geleuf geschrey und unrwe in unser kirchen. Man hyelt uns auch ganz hart an das der ganz Convent predig sollt horn und kein swester dy versaumen [...] es ryetten auch ettlich dapfer das man dy thur in die cappeln abprechen und eyn gitter dahin machen das wir also offenlich an der predigt mußten sitzen vor ydermann. [...] der prediger zu sant Lorenzen Osiander predigt alle suntag und feyertag pis auf michahely Aber wy gar uncristlich sy dy heilige geschrifft auf einen fremden syn zwungen [...] dy sy trewlich vermanten das sie uns gottlos volk ganz ausdilgten, dy closter zerrissen und uns mit gewalt auß den clostern sollten zern [...] haben auch dy prediger uns zu vergifften keinen fleiß gespart, aber mer sy uns predigten, ye mer wir merckten mit was lystiger falschheit und jrrthum sy umbgingen.",
         en="Am Donnerstag nach Judica sollte der Kartäuser zum ersten Mal predigen; da wurde er krank. Am Palmsonntag predigte der Prediger von Sankt Sebald, Dominicus, am Montag und Mittwoch der Prediger von Sankt Lorenz, Osiander, am Gründonnerstag der von Sankt Egidien, am Karfreitag und Ostertag Dominicus, am zweiten und dritten Ostertag Osiander, am Samstag der Kartäuser zum ersten Mal, am Sonntag Quasimodo Dominicus zum letzten Mal. So mussten wir die ganze Karwoche alle Prediger hören, damit man uns gleich mit Gewalt bekehrte, so dass wir nicht mehr ausweichen könnten. Wir hatten wahrlich eine schwere Karwoche, großen Zulauf, Geschrei und Unruhe in unserer Kirche. Man hielt uns auch sehr streng dazu an, dass der ganze Konvent die Predigt hören und keine Schwester sie versäumen solle [...] Einige rieten auch ernstlich, man solle die Tür zur Kapelle abbrechen und ein Gitter dahin machen, damit wir öffentlich vor jedermann bei der Predigt sitzen müssten. [...] Der Prediger von Sankt Lorenz, Osiander, predigte jeden Sonntag und Feiertag bis Michaeli. Aber wie unchristlich sie die Heilige Schrift in einen fremden Sinn zwangen [...] sie ermahnten die Leute treulich, uns gottloses Volk ganz auszutilgen, die Klöster zu zerreißen und uns mit Gewalt aus den Klöstern zu zerren [...] Die Prediger haben auch keinen Fleiß gespart, uns zu vergiften; aber je mehr sie uns predigten, desto mehr merkten wir, mit was für listiger Falschheit und Irrtum sie umgingen.",
         note="Poliander, nach Caritas ein verheirateter ehemaliger Chorherr aus Würzburg, hielt acht Predigten bis zum Dienstag nach Judica (Höfler S. 62, hier nicht abgedruckt); danach verordnete der Rat einen ehemaligen Kartäuser für zwei Wochentage und bis dahin die Prediger der Pfarrkirchen. Ostern war 1525 am 16. April. Andreas Osiander, Prediger an St. Lorenz, war nach der neueren Literatur der führende Kopf der Nürnberger Reformation; er predigte den Schwestern bis Michaeli (29. September). Was die Prediger sagten, kennen wir hier nur aus Caritas' zusammenfassender Klage, nicht aus ihren eigenen Worten."),
    dict(n=2, titel="Ein Beichtvater aus dem dritten Orden", pg="Höfler S. 71", lang="fnhd",
         orig="Unter des wart uns geratten von etlichen guten freuntten wir sollten uns erwellen einen frumen erbern prister, dem wir jn nötten möchten peichten als auf das wir nit als verechtern der heiligen sacrament geurtheilt würden, denn es was vil geschreys uber uns, wir wollten ee sterben ee wir ymant anders denn den parfussen wollten peichten, dieselbe maynung hielt ich dem convent fur, do es ye nit anders mocht sein, das wir keinem vater kunten peychten, do ryetten die swestern wir sollten herr Cunrat schrötter nennen, der was ein frumer tapferer prister pey 65 jarn alt, das thet wir auch mit rot und willen des würdigen vater quardian, die zeit Michel fryeß, der vergunt uns solchs und gab jm gewalt, das uns der vorgenant herr ein zeit vor wer und vergwist uns das wir darumb nit von dem orden unßer wurdigen veter gewichen wern als etliche swestern besorgt, nit denn dißer prister wer auch ein gelyd des ordens denn er hielt die dritt regel S. Francisci.",
         en="Unterdessen wurde uns von einigen guten Freunden geraten, wir sollten uns einen frommen, ehrbaren Priester wählen, dem wir in Nöten beichten könnten, damit man uns nicht als Verächterinnen der heiligen Sakramente verurteile; denn es gab viel Geschrei über uns, wir wollten lieber sterben, als jemand anderem als den Barfüßern zu beichten. Diese Meinung legte ich dem Konvent vor. Da es nun einmal nicht anders sein konnte, dass wir keinem Vater beichten konnten, rieten die Schwestern, wir sollten Herrn Konrad Schrötter nennen; das war ein frommer, tüchtiger Priester von etwa 65 Jahren. Das taten wir auch mit Rat und Willen des würdigen Vaters Guardian, damals Michael Fries; der erlaubte es uns und gab ihm Vollmacht, dass der genannte Herr uns eine Zeit lang vorstehe, und versicherte uns, dass wir darum nicht vom Orden unserer würdigen Väter gewichen seien, wie einige Schwestern fürchteten; denn dieser Priester sei auch ein Glied des Ordens, da er die dritte Regel des heiligen Franziskus hielt.",
         note="Der Ausweg, den der Konvent fand: kein Kandidat des Rates, sondern ein alter Weltpriester, der dem dritten Orden der Franziskaner angehörte, also Laien und Priestern in der Welt, und den der Guardian der Barfüßer selbst bevollmächtigte. So blieb das Band zum Orden wenigstens dem Namen nach bestehen. Wie lange Schrötter den Schwestern dienen durfte, erzählen spätere Teile."),
    dict(n=3, titel="Steine in den Chor; ‚wir hielten die Mette‘", pg="Höfler S. 84–87", lang="fnhd",
         orig="O da waren wir in großen engsten und notten, nacht und tag troet man uns wir wurden auch also mußen thun, do hetten wir uns vor mit einander vereint, das wir das closter in kein weg wollten aufgeben, dann wir hetten sein nit macht, es wer nit unser, wir hetten sein nit gepawt, Teglich troet man uns außzutreiben oder das closter zu pirchen oder zu verbrennen. [...] man hilt uns vil schmecher denn dy armen frawen hinter der maur, dann man predigt offenlich, wir wern erger den dieselben [...] wollten auch die leute nicht das man die closter mer closter sollt nennen, sunder spital; man sollt auch die swestern nicht swestern nennen sonder pfrundnerin, kein abtissin noch priorin sunder furweserin [...] Do wir nun also in vil engsten und notten warn [...] das wir kaum den gottlichen dinst dorfften halten, noch die glocken im Cor leuten, denn wenn man etwas von uns hört, so hub sich fluchen und schelten, schreyen in den kirchen herauf gegen uns, würffen mit steinen in unsern Chor und zerwurfen uns die fenster in den kirchen, und sungen schentliche lieder auf dem kirchhof, troetten uns offt, wenn wir noch ein nacht metten leuten, wollt man uns große ding thun, aber wir wagten es ymer auf die genad gottes, ließen kein nacht on geleut und ungehalten die metten [...] Die schwestern zu S. Katherin leuten woll zu einem halben jar kein metten.",
         en="O, da waren wir in großen Ängsten und Nöten; Tag und Nacht drohte man uns, wir würden es auch so machen müssen [wie die Männerklöster, die sich dem Rat übergaben]. Da hatten wir uns vorher miteinander verbunden, das Kloster keinesfalls aufzugeben, denn wir hätten keine Macht dazu, es sei nicht unser, wir hätten es nicht gebaut. Täglich drohte man, uns auszutreiben oder das Kloster zu stürmen oder zu verbrennen. [...] Man hielt uns für viel schmählicher als die armen Frauen hinter der Mauer, denn man predigte öffentlich, wir seien ärger als diese [...] Die Leute wollten auch nicht, dass man die Klöster noch Klöster nenne, sondern Spitäler; man solle die Schwestern auch nicht Schwestern nennen, sondern Pfründnerinnen, und keine Äbtissin oder Priorin, sondern Vorsteherin [...] Als wir nun so in vielen Ängsten und Nöten waren [...] dass wir kaum den Gottesdienst zu halten und die Glocken im Chor zu läuten wagten, denn wenn man etwas von uns hörte, so erhob sich Fluchen und Schelten und Schreien aus der Kirche herauf gegen uns; man warf mit Steinen in unseren Chor und zerwarf uns die Fenster in der Kirche und sang schändliche Lieder auf dem Kirchhof und drohte uns oft, wenn wir noch eine Nacht zur Mette läuteten, wolle man uns Großes antun. Aber wir wagten es immer auf die Gnade Gottes und ließen keine Nacht ohne Geläut und ungehalten die Mette [...] Die Schwestern zu Sankt Katharina läuteten wohl ein halbes Jahr keine Mette.",
         note="Zwischen Ostern und Pfingsten 1525 übergaben nach Caritas' Bericht das Benediktinerkloster St. Egidien, die Augustiner, Karmeliten und Kartäuser ihre Klöster dem Rat (ausgelassene Stelle); die Klarissen weigerten sich: Das Kloster ‚sei nicht unser, wir hätten es nicht gebaut‘. ‚Die armen Frauen hinter der Mauer‘ sind die Frauen im städtischen Frauenhaus. Die Gewalt in diesen Wochen ging von Leuten in der Kirche und auf dem Kirchhof aus, nicht vom Rat; dass der Rat die Prediger nicht mäßigte, ist Caritas' Vorwurf ([Artikel 3]). Die Mette ist das nächtliche Chorgebet."),
]

ARTIKEL = [
    dict(n=1, titel="Pfingstmittwoch 1525: die fünf Artikel des Rates", pg="Höfler S. 88–90", lang="fnhd",
         orig="Darnach am mitwoch in der pfingstwochen frw unter der prym kom herr sygmundt furer, sebalt pfintzing und endres imhof und begerten in das closter [...] hub der furer an zu reden: so durch das clar hell evangelisch gottswort nun öffenlich an den tag kumen wer, das die sunderlich sect als nemlich der geistlich absunderlich closterstandt ein verworffener jreziger sundtlicher verdampter standt wer [...] darumb die gemeyn also uber die geistlichen ergrympt wer, das sy schlecht kein closter noch geistlichen standt mer wollten leyden [...] und das wer auch die ursach des großen plutvergießens das yezunt geschech von den pawrn [...] Das erst das ein E. R. von mir als von der oberin wollet gehabt haben, das ich all swester yezunt sollt ledig zellen aller gelubt, die sy gethan hetten und sy lassen brauchen dy cristliche freiheit [...] Das 2, das ich kein swester uber jr willen sollt hynnen behalten, ich sollt auch den eltern jre kindt nit vorhalten, die sy nit hynnen wollten laßen, wenn schon der kindt will nit wer, dann es wider die gepod gottes, denn die kind wern ye schuldig jrn eltern gehorsam zu sein [...] Das 3 so wer der Rat und der gemeyn entliche maynung, das wir die kutten hynlegten und uns kleydeten wie ander leut [...] Das 4, so wer pei einem E. R. entlich beschlossen, das unsere redfenster nit allein redfenster sundern gesychtfenster sollten sein [...] und wer mit einer swester allein wollt reden, das sollt man geschehen lassen und die aufloserin sollt man hinweg heyssen gen [...] Das 5 [...] das wir selber ein inventarium sollten aufrichten und einem Rat das überantworten [...] Dyse Ding wollt E. E. R. also gehabt haben und zu disen dingen allen wollt man uns 4 wochen frist geben.",
         en="Danach, am Mittwoch in der Pfingstwoche, früh während der Prim, kamen Herr Sigmund Fürer, Sebald Pfinzing und Endres Imhof und begehrten ins Kloster [...] Fürer fing an zu reden: Da durch das klare, helle evangelische Gotteswort nun öffentlich an den Tag gekommen sei, dass die besondere Sekte, nämlich der geistliche, abgesonderte Klosterstand, ein verworfener, irriger, sündlicher, verdammter Stand sei [...] darum sei die Gemeinde so über die Geistlichen ergrimmt, dass sie schlechterdings kein Kloster und keinen geistlichen Stand mehr dulden wolle [...] und das sei auch die Ursache des großen Blutvergießens, das jetzt von den Bauern geschehe [...] Erstens wolle ein Ehrbarer Rat von mir als der Oberin, dass ich alle Schwestern jetzt aller Gelübde, die sie getan hätten, ledig spreche und sie die christliche Freiheit gebrauchen lasse [...] Zweitens, dass ich keine Schwester gegen ihren Willen drinnen behalten solle; ich solle auch den Eltern ihre Kinder nicht vorenthalten, wenn sie sie nicht drinnen lassen wollten, auch wenn es nicht der Wille des Kindes sei, denn das sei gegen Gottes Gebot, die Kinder seien ja schuldig, ihren Eltern gehorsam zu sein [...] Drittens sei es die endgültige Meinung des Rates und der Gemeinde, dass wir die Kutten ablegten und uns kleideten wie andere Leute [...] Viertens sei bei einem Ehrbaren Rat endgültig beschlossen, dass unsere Redefenster nicht nur Rede-, sondern Gesichtsfenster sein sollten [...] und wer mit einer Schwester allein reden wolle, dem solle man das gestatten und die Zuhörerin weggehen heißen [...] Fünftens [...] dass wir selbst ein Inventar aufrichten und einem Rat übergeben sollten [...] Diese Dinge wolle ein Ehrbarer Rat so haben, und für alle diese Dinge wolle man uns vier Wochen Frist geben.",
         note="Pfingsten 1525 war der 4. Juni, der Mittwoch also der 7. Juni. Sigmund Fürer ist der Onkel Margaretha Tetzels (Modul ‚Verhört man doch einen Dieb‘). Der zweite Artikel entscheidet den Fall Tetzel gegen die Tochter: Eltern dürfen ihre Kinder auch gegen deren Willen herausholen, ‚doch solle es alwegen vor einem Rat angesagt werden‘; wer geht, erhält ihr Eingebrachtes zurück oder ein Leibgeding, wer heiratet, eine Aussteuer (ausgelassene Sätze). Das ‚Gesichtsfenster‘ ist ein Sprechfenster, durch das man die Schwester sehen kann; die ‚Zuhörerin‘ (Aufloserin) war eine Mitschwester, die bei jedem Gespräch dabei saß."),
    dict(n=2, titel="‚Keine hat mir etwas gelobt, sondern Gott‘", pg="Höfler S. 91–92", lang="fnhd",
         orig="Do sy nun außgeredt, do antwurt ich auf den ersten artikel des gelubs halben. Es weß aller convent hye entgegen wol, das kein swester weder mir noch keinem lebendigen menschen auf erden gelobt het, sunder got dem almechtigen, darumb gezymet mir als einem armen menschen und unnuzen creatur in kein wegen das aufzulosen, das gott verpuntten wer [...] Darauß machten die herrn ein groß gespött, sagten wir fündens selbs in unser aygen gewissen und auch jn der heiligen geschrift das nichcz umb die gelüb wern [...] Darzu sagt ich was sy meiner person schuldig wern, wollt ich sy gern ledig sagen, dann ye keyne het mir nichcz gelobt, doch so fern das mich der Convent auch des ampts ledig sagt, dann ich west und kunt nit regyrn, wenn man mir nit gehorsam sollt sein, ich hett nun 22 jar mit meinen lieben kindern hauß gehalten [...] darzu wern etliche kinder hynnen, den jr Mütter an dem redfenster verputten, das sy nichcz sollten thun, was ich sy hieß, sy wern schuldig jn gehorsam zu sein und nit mir und meiner priorin.",
         en="Als sie ausgeredet hatten, antwortete ich auf den ersten Artikel, wegen der Gelübde: Der ganze hier anwesende Konvent wisse wohl, dass keine Schwester mir oder irgendeinem lebenden Menschen auf Erden etwas gelobt habe, sondern Gott dem Allmächtigen; darum gezieme es mir als einem armen Menschen und unnützen Geschöpf keineswegs, das aufzulösen, was Gott verbunden sei [...] Darüber machten die Herren großen Spott und sagten, wir fänden es selbst in unserem eigenen Gewissen und auch in der Heiligen Schrift, dass es mit den Gelübden nichts sei [...] Dazu sagte ich: Was sie meiner Person schuldig seien, davon wolle ich sie gern ledig sprechen, denn keine habe mir etwas gelobt; doch nur so, dass mich der Konvent auch des Amtes ledig spreche; denn ich wüsste nicht zu regieren und könnte es nicht, wenn man mir nicht gehorsam sein solle. Ich hätte nun zweiundzwanzig Jahre mit meinen lieben Kindern Haus gehalten [...] Dazu seien einige Kinder hier drinnen, denen ihre Mütter am Redefenster verboten hätten, etwas zu tun, was ich ihnen hieße; sie seien schuldig, ihnen gehorsam zu sein und nicht mir und meiner Priorin.",
         note="Die Logik der Antwort: Ein Gelübde gilt Gott, also kann keine Äbtissin es lösen; was die Schwestern ihr persönlich schulden, gibt sie gern frei, dann aber auch ihr Amt. ‚Zweiundzwanzig Jahre‘: Äbtissin seit 1503. Im Kloster gab es schon Schwestern, denen ihre Mütter am Sprechfenster Gehorsam gegen die Äbtissin verboten: Der Riss ging durch die Familien in den Konvent hinein. Der Rat antwortete (ausgelassen), im Haushalt sollten sie ihr folgen, zu Fasten, Gebet oder Gelübde aber dürfe sie keine anhalten."),
    dict(n=3, titel="Die Kutten, die Prediger, das Gesichtsfenster", pg="Höfler S. 92–93", lang="fnhd",
         orig="Item der cleydung halber, sprach ich, wir westen wol, das uns die kutten nicht selig machet, westen aber auch wol das das himelreich nit jn den schumelten schauben stund [...] Sagten sy, wir sollten die kutten zertrennen und anders lassen ferben [...] es wurd doch das closter on das abgen, so würd man uns in kein weg furpas ewiglich nymant mehr vergunen einzunemen, darumb sollten wir nernt reychlich zern mit essen und trinken und claydern, es wirdt dennoch gut und gelt überbeleiben, wen wir all stürben. [...] Sprach ich unter andern worten, lieber herr, jr sagt ymer, wir wern mit unsern gelubden und claydern ursach geben zu einem auflawf, ich furcht mer, das ewr prediger, die wir horn mussen, gern ein solchs verursachten, so sy uns stettiglich auf der canzel also schenten und lestern [...] dann wir sizen manchmals an der predig das wir all zyttern und all augenplick müssen warten wenn man uns das Closter aufstest [...] Aber Sygmundt Furer spottet mein dazu, saget, man prediget die ding nit allein auf unser Canzel sunder durch die ganze Welt [...] Item des gesychtfensters und alleinredens halb het ich zumal einen großen streit mit jn, sprach unter andern: ich merket woll, das sy ein offenes closter wollten machen.",
         en="Wegen der Kleidung sprach ich: Wir wüssten wohl, dass uns die Kutte nicht selig mache; wir wüssten aber auch wohl, dass das Himmelreich nicht in den verbrämten Schauben stehe [...] Sie sagten, wir sollten die Kutten auftrennen und anders färben lassen [...] das Kloster werde ohnehin eingehen, denn man werde uns künftig auf ewig niemanden mehr aufzunehmen erlauben; darum sollten wir nur reichlich zehren mit Essen, Trinken und Kleidern, es werde trotzdem Gut und Geld übrig bleiben, wenn wir alle gestorben seien. [...] Ich sprach unter anderem: Lieber Herr, Ihr sagt immer, wir gäben mit unseren Gelübden und Kleidern Ursache zu einem Aufruhr; ich fürchte mehr, dass Eure Prediger, die wir hören müssen, gern so etwas verursachen würden, da sie uns ständig auf der Kanzel so schänden und lästern [...] denn wir sitzen manchmal so bei der Predigt, dass wir alle zittern und jeden Augenblick warten müssen, dass man uns das Kloster aufstößt [...] Aber Sigmund Fürer spottete darüber und sagte, man predige diese Dinge nicht allein auf unserer Kanzel, sondern in der ganzen Welt [...] Wegen des Gesichtsfensters und des Alleinredens hatte ich vollends einen großen Streit mit ihnen und sprach unter anderem: Ich merke wohl, dass sie ein offenes Kloster machen wollten.",
         note="Hier steht zum ersten Mal ausgesprochen, was das Schicksal des Klosters wurde: keine Novizinnen mehr, ‚auf ewig‘, also ein Aussterben auf Raten; die Herren sagen es fast heiter (‚zehrt nur reichlich‘). ‚Schauben‘ sind die weiten Mäntel der Bürger. Die Gegenrede der Äbtissin dreht den Vorwurf um: Nicht die Kutten, sondern die Predigten gegen die Schwestern gefährdeten den Frieden der Stadt."),
    dict(n=4, titel="Der Konvent stimmt: die Regel, die wir Gott gelobt haben", pg="Höfler S. 94–96", lang="fnhd",
         orig="Do sy nun auß dem closter komen, fodert ich den Convent zu capitel [...] begert von einem ytlichen in sunderheit zu wissen, wes ich mich gegen jn versehen sollt, ob sy die regel wollten annemen, die jn die herrn geben hetten. Also stymenten sy alle einhelliglich, ein ytliche insunderheit keine ausgenommen, das sy mit der hilf gottes halten wollten die Regel die sy Gott gelobt hetten und gar nit die Regel, die jn der Rat geben hat und erpitten sich gar demutiglich und williglich, sy begerten nit frey zu sein, sy wollten mir gern gehorsam sein [...] das ich neyr pei jn belib und sy in den engsten und notten nit ließ. Also gelobte ich jn auch wider umb trew zu laysten pey jn zu beleiben und leib und leben pey jn zu lassen pis in den todt, solang sy standhaftig belieben jn den warn cristlichen glauben und in dem geistlichen standt. [...] Wir protestirten auch do conventlich vor dem lebendigen gotte, das wir mit willen nichcz wollten aufnemen, das wider gott und unsern heilig regel wer, würden wir aber zu etwas gezwungen wider unsern willen, begerten wir unser herr ansehe, das wir gewalt müsten leyden [...] Item des gesichtfensters halben stymten die swestern wiewol sy es gancz nit begerten, doch so es nit anders möcht sein [...] sollt ich ein eynigs redfenster zu einem gesychtfenster machen lassen [...] es meldent vil swestern des alleinredens halb, sy begerten desselb gar nit, sy hetten nichcz mit jrn freunten zu reden, des sy sich vor den hörern scheuchten, es wer ferlich mit weltlichen Leuten allein zu reden, dann man möcht von uns sagen sie hetten geredt, das sy jn nye gedacht hetten.",
         en="Als sie nun aus dem Kloster gekommen waren, rief ich den Konvent zum Kapitel [...] und verlangte von jeder einzeln zu wissen, wessen ich mich bei ihnen versehen solle, ob sie die Regel annehmen wollten, die ihnen die Herren gegeben hätten. Da stimmten sie alle einhellig, jede einzeln, keine ausgenommen, dass sie mit Gottes Hilfe die Regel halten wollten, die sie Gott gelobt hätten, und gar nicht die Regel, die ihnen der Rat gegeben habe; und sie erboten sich ganz demütig und willig, sie begehrten nicht frei zu sein, sie wollten mir gern gehorsam sein [...] wenn ich nur bei ihnen bliebe und sie in den Ängsten und Nöten nicht verließe. So gelobte ich ihnen auch meinerseits Treue, bei ihnen zu bleiben und Leib und Leben bei ihnen zu lassen bis in den Tod, solange sie standhaft im wahren christlichen Glauben und im geistlichen Stand blieben. [...] Wir protestierten auch im Konvent vor dem lebendigen Gott, dass wir mit Willen nichts annehmen wollten, was gegen Gott und unsere heilige Regel sei; würden wir aber zu etwas gegen unseren Willen gezwungen, so begehrten wir, dass unser Herr ansehe, dass wir Gewalt leiden müssten [...] Wegen des Gesichtsfensters stimmten die Schwestern, obwohl sie es ganz und gar nicht begehrten: Wenn es nicht anders sein könne [...] solle ich ein einziges Redefenster zu einem Gesichtsfenster machen lassen [...] Viele Schwestern sagten wegen des Alleinredens, sie begehrten es gar nicht, sie hätten mit ihren Verwandten nichts zu reden, wofür sie sich vor den Zuhörerinnen scheuten; es sei gefährlich, mit weltlichen Leuten allein zu reden, denn man könne von uns sagen, sie hätten geredet, was sie nie gedacht hätten.",
         note="Die Abstimmung ‚jede einzeln‘ ist die Antwort auf den Vorwurf, die Äbtissin mache den Konvent widerspenstig ([Pfleger 5]). Der Konvent gibt nach, wo die Regel es zulässt: ein Gesichtsfenster. Bei der Kleidung rieten ‚gute Freunde‘ im Rat zu warten (ausgelassen); das Gesichtsfenster hatten nach Caritas die dem Kloster gewogenen Ratsherren Martin Geuder, Hieronymus Holzschuher und Jakob Muffel vorgeschlagen, um den freien Zutritt zu den Frauenklöstern zu verhindern, den der Rat schon beschlossen hatte. Drei Tage später ließen Ebner und Nützel ihren Töchtern ausrichten, sie würden sie holen (Modul ‚Da stee ich‘)."),
]

doc = {
    "id": "prediger",
    "titel": "Die Väter genommen, die Prediger geschickt, März bis Juni 1525",
    "autor": "Caritas Pirckheimer; Kaspar Nützel; der Konvent von St. Klara",
    "jahr": "19. März bis 7. Juni 1525",
    "sprache": "de",
    "orig_sprache": "fnhd",
    "pg_label": "",
    "quelle": "C. Höfler (Hg.), Der hochberühmten Charitas Pirkheimer, Aebtissin von S. Clara zu Nürnberg, Denkwürdigkeiten aus dem Reformationszeitalter (Quellensammlung für fränkische Geschichte 4, Bamberg 1852), S. 33–58, 69–71, 84–96 in Auswahl (Internet Archive: 11420769bsb). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Ein Auswahlmodul: Höflers S. 33–97 enthalten neben den hier gedruckten Stücken weitere Bittschriften und Briefe des Pflegers (Nr. 15–22), die ein späteres Modul aufnehmen kann. Der frühneuhochdeutsche Text ist am Seitenbild gelesen. Höflers erklärende Zusätze in runden Klammern sind weggelassen, Ergänzungen der Übersetzung stehen in eckigen Klammern, ‚&c.‘ steht für ‚ꝛc.‘. Auslassungen sind mit [...] bezeichnet. Die Übersetzung ist eigene Arbeit (CC0).",
    "sections": [
        {"id": "oculi", "autor": "Caritas Pirckheimer", "titel": "Sonntag Oculi, 19. März 1525", "zk": "Oculi",
         "plates": ["hoefler_s33"],
         "blurb": "Zwei Gesandte des Rates verkünden dem Konvent drei Beschlüsse: ein Prediger des Rates, ein Beichtvater aus drei Kandidaten des Rates, keine Barfüßer mehr. Die Äbtissin protestiert vor Gott, der Konvent steht auf und bezeugt es. Noch am selben Abend gehen die Väter; seither sind die Schwestern ohne Sakramente.",
         "units": OCULI},
        {"id": "pfleger", "autor": "Caritas Pirckheimer; Kaspar Nützel; der Konvent", "titel": "Der Pfleger im Konvent, 23. bis 25. März", "zk": "Pfleger",
         "plates": ["hoefler_s51"],
         "blurb": "Kaspar Nützel kommt auf Bitte des Konvents und predigt ihm: Die ganze Stadt sei der neuen Meinung, die Bauern sammelten sich. Die Äbtissin bietet an hinauszugehen, damit er die Schwestern allein höre; er will nicht. Die Bittschrift: im Leib verschlossen, aber nicht im Gewissen gefangen. Eine Stunde allein im Chor: ‚wenn sie mich allein hätten, so hätten sie die ganze Landschaft‘.",
         "units": PFLEGER},
        {"id": "prediger", "autor": "Caritas Pirckheimer", "titel": "Die Prediger, Karwoche bis Pfingsten", "zk": "Prediger",
         "plates": ["osiander1544", "lorenz1685"],
         "blurb": "In der Karwoche müssen die Schwestern alle Prediger der Stadt hören, unter ihnen Andreas Osiander, und zwar vollzählig. Die Männerklöster übergeben sich dem Rat; die Klarissen weigern sich. Man wirft Steine in ihren Chor; sie läuten trotzdem jede Nacht zur Mette.",
         "units": PREDIGER},
        {"id": "artikel", "autor": "Caritas Pirckheimer; der Konvent", "titel": "Die fünf Artikel, Pfingstmittwoch 1525", "zk": "Artikel",
         "plates": ["hoefler_s89"],
         "viz": "forderungen",
         "blurb": "Sigmund Fürer, Sebald Pfinzing und Endres Imhof bringen die Forderungen des Rates: die Gelübde lösen, die Töchter den Eltern herausgeben, die Kutten ablegen, Gesichtsfenster einrichten, das Gut inventarisieren, in vier Wochen. Die Äbtissin: Gelübde gelten Gott, nicht ihr. Der Konvent stimmt einzeln, keine ausgenommen.",
         "units": ARTIKEL},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("prediger.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
