"""Modul 5: Da stee ich. Die Töchter, Juni 1525. Schreibt data/toechter.json.

Quelle, am Seitenbild gelesen: C. Höfler (Hg.), Denkwürdigkeiten der Charitas
Pirkheimer (Bamberg 1852), S. 97-111 (Internet Archive 11420769bsb; S. n =
Blatt n+118). Höflers Klammerzusätze sind weggelassen.
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "toechter.json"

VORHER = [
    dict(n=1, titel="Samstag vor Trinitatis: die Väter lassen es ausrichten", pg="Höfler S. 97", lang="fnhd",
         orig="Darnach am Samstag der heiligen Tryvaltigkeit abend da entpot herr Jeronimus Ebner und unser pflegherr Caspar Nuzel jhre tochter pey uns katharina ebnerin und clara nuzlin, nachdem E. E. R. uns gepoten het unsere klayder zu verendern törften sy sich nit anders clayden, dann sy wollten sy auf die kunftig wochen holn lassen und sy selber claydn. O do hub sich angst und not und herzenleid um die armen kind, man kann nit gelauben, was sy von derselben stund an für ein elende zeit haben gehabt, wiewol sy dennoch ymer hofften, sy wollten sich erretten.",
         en="Danach, am Samstag, dem Vorabend der Heiligen Dreifaltigkeit, ließen Herr Hieronymus Ebner und unser Pfleger Kaspar Nützel ihren Töchtern bei uns, Katharina Ebnerin und Clara Nützlin, ausrichten: Nachdem ein Ehrbarer Rat uns geboten habe, unsere Kleider zu ändern, bräuchten sie sich nicht anders zu kleiden, denn sie wollten sie in der kommenden Woche holen lassen und selbst kleiden. O, da erhob sich Angst und Not und Herzeleid um die armen Kinder; man kann nicht glauben, was für eine elende Zeit sie von dieser Stunde an gehabt haben, obwohl sie immer noch hofften, sie würden sich retten.",
         note="Trinitatis war 1525 der 11. Juni, der Samstagabend also der 10. Juni, drei Tage nach den fünf Artikeln (Modul ‚Die Väter genommen‘). Die Väter sind zwei der mächtigsten Männer der Stadt: Hieronymus Ebner, an den Caritas im Advent geschrieben hatte und dessen Tochter Katharina damals den Brief für sie schrieb, und der Pfleger des Klosters selbst. Der Anlass ist der dritte Artikel, die Kleider: Wenn die Kutten fallen sollen, kleiden die Väter ihre Töchter lieber selbst."),
    dict(n=2, titel="Montag: die Mütter am Tor", pg="Höfler S. 97–99", lang="fnhd",
         orig="Am montag darnach kam die Jeronymus ebnerin, Caspar nuzlin und Friderich tezlin, sigmundt furerin auf einem wagen gefaren, wollten mit gewalt herein in das closter. Do ich jn das abschlug [...] Sprach ich, wenn ir hereinget, so wöllen andere leut auch hereingin, die kynder hynnen haben, damit wird das closter geöffnet, das will ich mit der hilf des lebendigen gottes nit leiden dieweil es mir zugehört. Da sy sahen, das ich sy ye nit herein wollt lassen, da wollten sy doch mit gwalt, das ich jn ire kinder jn die kirchen hinauß ließ gin, das sy frey mit jn möchten reden von gots wort und der sel heil. Das wollt ich jn auch nit gestatten [...] Sprach ich, die Kinder hetten begert jre veter das sy vor jre maynung hörten, wurden sy zornig, sagten, was es ire veter anging, sie hetten die kinder getragen und wern jn sauer worden, sie westen wol was sy theten und wes sy befelh hatten. [...] Sprach die ebnerin, sy müst eins allein für sich haben, ee sy jr tochter genugsam in gots wort unterrichtet. Nach langem gezenk erpot ich mich, ich wollt sy allein mit jr tochter lassen reden an dem redfenster oder in der capeln an dem Fensterlein, do man uns das heilig sacrament geb oder wo sy sust wollten. Das wollten sy gar nit thun, sie wern nit sicher in der capeln das man jn nit zuhöret und zürneten auf das höchst, wollten die kinder nit zu jn lassen kumen, sagten mit viel troworten, sy wollten auf dyßmal hinscheyden und wollten gewalth genug pringen das ichs müst jnnen werden.",
         en="Am Montag danach kamen die Hieronymus Ebnerin, die Kaspar Nützlin und die Friedrich Tetzlin, die Sigmund Fürerin, auf einem Wagen gefahren und wollten mit Gewalt herein ins Kloster. Als ich ihnen das abschlug [...] sprach ich: Wenn ihr hereingeht, so wollen andere Leute, die Kinder hier drinnen haben, auch hereingehen; damit wird das Kloster geöffnet, und das will ich mit der Hilfe des lebendigen Gottes nicht leiden, solange es mir zusteht. Als sie sahen, dass ich sie nicht hereinlassen wollte, wollten sie doch mit Gewalt, dass ich ihnen ihre Kinder in die Kirche hinausgehen ließe, damit sie frei mit ihnen von Gottes Wort und dem Seelenheil reden könnten. Das wollte ich ihnen auch nicht gestatten [...] Ich sprach, die Kinder hätten begehrt, dass ihre Väter vorher ihre Meinung hörten. Da wurden sie zornig und sagten, was gehe es die Väter an, sie hätten die Kinder getragen, und sie seien ihnen sauer geworden; sie wüssten wohl, was sie täten und welchen Befehl sie hätten. [...] Die Ebnerin sprach, sie müsse ein Fenster allein für sich haben, bis sie ihre Tochter genügend in Gottes Wort unterrichtet habe. Nach langem Gezänk erbot ich mich, sie allein mit ihrer Tochter reden zu lassen, am Redefenster oder in der Kapelle an dem Fensterlein, durch das man uns das heilige Sakrament gibt, oder wo sie sonst wollten. Das wollten sie gar nicht tun: Sie seien in der Kapelle nicht sicher, dass man ihnen nicht zuhöre; sie zürnten aufs Höchste, wollten die Kinder nicht zu sich kommen lassen und sagten mit vielen Drohworten, sie wollten für diesmal gehen und genug Gewalt bringen, dass ich es zu spüren bekäme.",
         note="Montag, 12. Juni 1525. Vier Frauen auf einem Wagen: die Mütter Katharina Ebners und Clara Nützels, Ursula Tetzel (Modul ‚Verhört man doch einen Dieb‘) und die Frau Sigmund Fürers, ihre Schwägerin. ‚Sie hätten die Kinder getragen, und sie seien ihnen sauer geworden‘: der Anspruch der Mütter, in ihren eigenen Worten, wie Caritas sie wiedergibt. Die Äbtissin bietet, wie im Februar, das Gespräch allein am Fenster an; die Mütter lehnen ab, weil sie fürchten, belauscht zu werden. Ausgelassen ist ein Wortwechsel über das Gesichtsfenster, das der Rat am 7. Juni mit vier Wochen Frist verlangt hatte."),
    dict(n=3, titel="Dienstag: die Klage vor dem Rat und sein Befehl", pg="Höfler S. 99–101", lang="fnhd",
         orig="An eritag verklagten sie mich heftiglich vor eym ganzen Rat durch Nyclaß haller, der war jr advokat, wie ich so spizig, stolz und heftig mit jn gehandelt het, wie ich jn jre kinder mit gewalt wider eins E. R. befehl vorgehalten het, wie ich sy weder wenig noch vil mit jrn kindern het wollen lassen reden, wie ich sy het lyegen heyssen [...] An demselben tag nach tisch schickt man mir 2 rotherren, sebolt pfinzing und endres im hoff, die sagten mir das Capitel wie mich die frawen verklagt hetten und wie E. E. R. so hart uber mich erzürnt wer [...] darumb wer eins Rats entliche meynung und befelh so die leut jr kint nit lenger pey uns wollten wissen, so sollten wir wissen das die mütter jre kind des andern tags wollten holen, so sollt ich jn die frey on alles widerred geben, das und kein anders das wollt E. E. R. gehabt haben, es wer halt den kindern lieb oder leyd. Sagt ich jn, die sach het sich nit also verloffen, wie E. E. R. angesagt wer worden. [...] hub doch an und saget jn nach warheit, wie alle ding mit den frawen ergangen wern, hetten sy ein groß wunder daran, sagten es wer E. E. R. gar vil heftiger und anders gesagt worden [...] Saget ich jn, wie die kinder es herzlich begerten, das man jn jr 2 veter heraushieß ee die muter wieder kemen, das sy doch jr notturft mit jn möchten reden, sprachen sy, es wird eigentlich nit geschehen, wenn sy nun in jr veterhauß kemen, würden sy dennoch zeit genugt haben mit jrn vetern zu reden. Pat ich sy zuletzt, daß sy einen E. R. mein Antwurt widersagten und mich jn der unpillichen anclag mit warheit entschuldigten, das hetten sy getrewlich gethan. Do het man den Nyclas haller gefragt warumb er E. E. R. so ungleiche ding het furpracht, het er gesagt er het nichcz furpracht, denn was jm die weiber hetten gesagt [...]",
         en="Am Dienstag verklagten sie mich heftig vor einem ganzen Rat durch Niklas Haller, der war ihr Anwalt: wie ich so spitz, stolz und heftig mit ihnen umgegangen sei, wie ich ihnen ihre Kinder mit Gewalt gegen den Befehl eines Ehrbaren Rats vorenthalten habe, wie ich sie weder wenig noch viel mit ihren Kindern habe reden lassen wollen, wie ich sie Lügnerinnen geheißen habe [...] Am selben Tag nach Tisch schickte man mir zwei Ratsherren, Sebald Pfinzing und Endres Imhof; die lasen mir das Kapitel, wie mich die Frauen verklagt hätten und wie ein Ehrbarer Rat so hart über mich erzürnt sei [...] Darum sei es die endgültige Meinung und der Befehl des Rates: Wenn die Leute ihre Kinder nicht länger bei uns wissen wollten, so sollten wir wissen, dass die Mütter ihre Kinder am folgenden Tag holen wollten, und ich solle sie ihnen frei ohne jede Widerrede geben; das und nichts anderes wolle ein Ehrbarer Rat, es sei den Kindern lieb oder leid. Ich sagte ihnen, die Sache habe sich nicht so zugetragen, wie es einem Ehrbaren Rat angesagt worden sei [...] und begann, ihnen nach der Wahrheit zu sagen, wie alles mit den Frauen ergangen sei. Darüber wunderten sie sich sehr und sagten, es sei einem Ehrbaren Rat viel heftiger und anders gesagt worden [...] Ich sagte ihnen, wie die Kinder herzlich begehrten, dass man ihre zwei Väter herauskommen lasse, ehe die Mütter wiederkämen, damit sie doch ihre Notdurft mit ihnen reden könnten. Sie sprachen, das werde gewiss nicht geschehen; wenn sie nun in ihr Vaterhaus kämen, würden sie dennoch Zeit genug haben, mit ihren Vätern zu reden. Zuletzt bat ich sie, einem Ehrbaren Rat meine Antwort wiederzusagen und mich in der unbilligen Anklage mit Wahrheit zu entschuldigen; das haben sie treulich getan. Da hat man Niklas Haller gefragt, warum er einem Ehrbaren Rat so ungleiche Dinge vorgebracht habe; er hat gesagt, er habe nichts vorgebracht als das, was ihm die Weiber gesagt hätten [...]",
         note="Dienstag, 13. Juni. Der Rat entscheidet über das Kloster wieder, ohne es vorher zu hören: auf die Klage der Mütter durch ihren Anwalt. Pfinzing und Imhof hören die Äbtissin erst nachher und berichten ihre Darstellung zurück. Der Befehl selbst wird nicht zurückgenommen: ‚es sei den Kindern lieb oder leid‘. Die Töchter wollten ihre Väter sprechen, ehe die Mütter wiederkämen; das wird abgelehnt. Ausgelassen sind die Vorwürfe im Einzelnen, Caritas lasse ‚sonst andere Frauen‘ ins Kloster, und ihre Antwort, sie wehre den Eingang auf Befehl des Rates selbst, der ihr ein ‚offenes Kloster‘ zu verhindern versprochen habe."),
]

FRONLEICHNAM = [
    dict(n=1, titel="Mittwoch, Vorabend von Fronleichnam: ‚in derselben Stunde‘", pg="Höfler S. 101–102", lang="fnhd",
         orig="Am mitwoch sant veits abend was auch unsers lieben herrn fronleichnams abent welchem allerheiligsten tag weder feyret noch beging noch die allermynste reverenz dem hochwürdigen sacrament bewyeß do schickten die poßen weiber ein stund vor essenszeit zu mir, sy wollten unter essens komen und die kinder holen, wollten auch ander leut mit jn pringen, das ich seh das sy gewalt genugs hetten. Do schickt ich pald auf das Rathhauß und begeret, das man mir 2 zeugen schicket [...] Aber die armen kinder westen noch nit eigentlich wenn es geschehen würd, hetten vil anschlag hofften noch ymmer wenn es schon an das treffen ging, sy wollten sich noch erretten, man würd jn wider jrn willen keinen solchen gewalt anlegen, Aber do ich sy beruft und jn saget jr müttern würn sie in derselben stund holn, do fyelen sie alle drey auf das ertreich und schryen, weinten und heulten. und hetten solch cleglich geperdt, es möcht got in himel erparmt haben, sye wern gern geflohen und hetten sich verporgen. Das wollt ich jnen nicht gestatten, dann wir besorgten, man wurd mit gewalt hereinlaufen und sy an allen orten suchen und das ungelück noch größer wern, desgeleichen weynet und claget der ganze convent.",
         en="Am Mittwoch, dem Vorabend von Sankt Veit, das war auch der Vorabend des Fronleichnams unseres lieben Herrn, welchen allerheiligsten Tag man weder feierte noch beging noch dem hochwürdigen Sakrament die allermindeste Ehrfurcht erwies, schickten die bösen Weiber eine Stunde vor der Essenszeit zu mir: Sie wollten während des Essens kommen und die Kinder holen und auch andere Leute mitbringen, damit ich sähe, dass sie Gewalt genug hätten. Da schickte ich sogleich aufs Rathaus und begehrte, man möge mir zwei Zeugen schicken [...] Aber die armen Kinder wussten noch nicht genau, wann es geschehen würde, hatten viele Pläne und hofften immer noch, auch wenn es zum Treffen käme, sie würden sich noch retten, man würde ihnen gegen ihren Willen keine solche Gewalt antun. Als ich sie aber rief und ihnen sagte, ihre Mütter würden sie in derselben Stunde holen, da fielen sie alle drei zu Boden und schrien, weinten und heulten und gebärdeten sich so kläglich, dass es Gott im Himmel hätte erbarmen mögen. Sie wären gern geflohen und hätten sich versteckt. Das wollte ich ihnen nicht gestatten, denn wir fürchteten, man würde mit Gewalt hereinlaufen, sie an allen Orten suchen, und das Unglück würde noch größer. Ebenso weinte und klagte der ganze Konvent.",
         note="Mittwoch, 14. Juni 1525; Fronleichnam fiel 1525 auf den 15. Juni, den Veitstag. Dass Nürnberg Fronleichnam 1525 nicht mehr beging, gehört zur Reformation der Stadt. ‚Die bösen Weiber‘: Caritas' eigenes Wort für die Mütter, in diesem Teil mehrfach; sie nennt sie auch ‚grimmige Wölfinnen‘. Die Zeugen vom Rathaus hatte sie selbst erbeten, damit nicht wieder nur die Mütter berichteten. Die Äbtissin verbietet den Töchtern, sich zu verstecken: Sie hätte das Kloster der Durchsuchung ausgesetzt."),
    dict(n=2, titel="Drei Schwestern", pg="Höfler S. 101–102", lang="fnhd",
         orig="dann es sind frume geschickte kinder gewest, die sich wol pey uns gehalten haben und sy von herzen und sel ungern von uns schyden. Schwester margaret tezlin war 23 jar alt und 9 jar im heiligen orden gewest, katherina ebnerin und Clara nuzlin komen ped an einem tag in den heiligen orden, theten auch an einem tag profeß auf inventionis sancte crucis was 6 jar gewest, das sy in das closter kumen warn, katharina ebnerin war 20. jar alt, clara nuzlin 19 jar alt. Da man sy hinauß nem, theten wir jn mit vil zehern die weyler und seyl ab und die weissen röck, legten jn hemdlein an und weltlich gürtel und auflegerley auf das haubt, fur ich sy mit etlichen Rotswestern in die capeln.",
         en="Denn es sind fromme, geschickte Kinder gewesen, die sich gut bei uns gehalten haben und von Herzen und Seele ungern von uns schieden. Schwester Margaret Tetzlin war 23 Jahre alt und 9 Jahre im heiligen Orden gewesen; Katharina Ebnerin und Clara Nützlin kamen beide an einem Tag in den heiligen Orden und taten auch an einem Tag Profess, am Fest der Kreuzauffindung; es waren sechs Jahre, seit sie ins Kloster gekommen waren. Katharina Ebnerin war 20 Jahre alt, Clara Nützlin 19 Jahre alt. Als man sie hinausnahm, nahmen wir ihnen unter vielen Tränen die Schleier und die Stricke und die weißen Röcke ab, legten ihnen Hemdlein an und weltliche Gürtel und eine Haube auf das Haupt, und ich führte sie mit einigen Ratsschwestern in die Kapelle.",
         note="Die drei Ältesten waren also mit vierzehn, vierzehn und dreizehn Jahren ins Kloster gekommen; Ursula Tetzel hatte das in ihrer Klage ‚unverständige Jahre‘ genannt (Modul ‚Verhört man doch einen Dieb‘). Das ist die Seite des Klosters, die die Mütter angriffen: Kinder, die vor der Mündigkeit eintraten und ein Gelübde auf Lebenszeit ablegten. Das Fest der Kreuzauffindung ist der 3. Mai. Die Schwestern selbst ziehen den Töchtern das Ordenskleid aus, bevor die Mütter kommen. ‚Ratsschwestern‘ sind die älteren Schwestern, mit denen sich die Äbtissin beriet. ‚Auflegerley‘ ist wohl eine weltliche Haube."),
    dict(n=3, titel="Die Menge auf dem Kirchhof; ‚nicht heimlich‘", pg="Höfler S. 102–103", lang="fnhd",
         orig="So warteten wir wol eine ganze stund pis die grimmigen wölfin gefarn komen auf 2 kamerwagen. Dieweil war das geschrey unter das gemein volk kumen, dy samelten sich in großer meng als wen man einen armen menschen will ausfürn, stund die ganz gassen und kirchhof voll [...] Do schembten sy sich, das so vil volk do war, hetten gern gesehen das wirs zum hintern thor jm garten hinaus hetten thun, schickten desselben halber die 2 herrn sebolt pfinzing und endres im hoff zu mir [...] do wollt ichs nicht thun, ich wollt nit heymlich mit der sach umbgen, sprach theten sy recht, so törfften sy sich nit schemen, ich wollt sy an keinem andern ort hinauß geben, denn da ich sy herein het genumen, das war durch die cappelnthür. [...] sprach ich zu den herrn, so get jr herein und redt mit jn, das sys gern thun, ich kann und will sye nit notten zu dem das jn von sel und herczen wider ist. Also gingen die 2 herrn herein, sprach ich, da stell ich euch meine arme waißlein wie jr mir gestern von Rats wegen gepotten habt und befelh sy dem obersten hyrten, der sy mit seinem tewrn plut erlost hat, gesegenten an einander, mit unzelligen heyßen zehern fielen die kinder alle umb mich [...] Aber ich kunt jn leider nit helfen, ging ich mit den Swestern davon und ließ dy armen kind allein jn der cappeln.",
         en="So warteten wir wohl eine ganze Stunde, bis die grimmigen Wölfinnen auf zwei Kammerwagen gefahren kamen. Unterdessen war das Geschrei unter das gemeine Volk gekommen; die sammelten sich in großer Menge, wie wenn man einen armen Menschen zur Hinrichtung ausführen will; die ganze Gasse und der Kirchhof standen voll [...] Da schämten sie sich, dass so viel Volk da war, und hätten gern gesehen, dass wir sie zum hinteren Tor im Garten hinausgelassen hätten; deswegen schickten sie die zwei Herren Sebald Pfinzing und Endres Imhof zu mir [...] Das wollte ich nicht tun; ich wollte nicht heimlich mit der Sache umgehen und sprach: Täten sie recht, so bräuchten sie sich nicht zu schämen; ich wolle sie an keinem anderen Ort hinausgeben als dort, wo ich sie hereingenommen hätte, das war durch die Kapellentür. [...] Ich sprach zu den Herren: So geht Ihr herein und redet mit ihnen, dass sie es gern tun; ich kann und will sie nicht zu dem nötigen, was ihnen von Seele und Herzen zuwider ist. So gingen die zwei Herren herein, und ich sprach: Da stelle ich Euch meine armen Waislein, wie Ihr mir gestern im Namen des Rates geboten habt, und befehle sie dem obersten Hirten, der sie mit seinem teuren Blut erlöst hat. Wir segneten einander; unter unzähligen heißen Tränen fielen die Kinder alle um mich [...] Aber ich konnte ihnen leider nicht helfen; ich ging mit den Schwestern davon und ließ die armen Kinder allein in der Kapelle.",
         note="Zweimal derselbe Vergleich: Die Menge stand da ‚wie wenn man einen armen Menschen ausführt‘, also wie bei einer Hinrichtung. Caritas besteht auf der Öffentlichkeit, wie sie es im Februar für Margaretha verlangt hatte (Modul ‚Verhört man doch einen Dieb‘): nicht durch das Gartentor, sondern durch die Tür, durch die die Töchter einst hereinkamen. Sie gehorcht dem Befehl des Rates, aber sie selbst schickt niemanden hinaus. Ausgelassen ist, dass die Mütter die Kirche räumen und abschließen ließen."),
    dict(n=4, titel="‚Du bist eine Mutter meines Fleisches und nicht meines Geistes‘", pg="Höfler S. 103–104", lang="fnhd",
         orig="Da lyeffen die pößen weiber herein als die grimige wölfin, die friz tezlin mit einer tochter, jeronymus ebnerin, sigmundt furerin, unser pflegerin Caspar nutzlin mit jrn pruder linhart helt, der an des pflegers stat da war und auch des sebolt pfinzing sönlein &c. De hießen die weyber die kinder hinauß gen mit guten worten, wollten sy es aber nit gutlich thun, so wollten sye mit gewalt hinauß zerren [...] Sprachen die mütter zu den kindern sy wern jn schuldig gehorsam zu sein nach gottes gepot, sy wollten gehabt haben das sy hynauß gingen, dann sy wern darumb da, das sy ir sel auß der hell wollten erloßen, sy sessen dem teufel in den rachen, das kunnten sy nimer on jr gewissen erleyden, schryen die kinder sy wollten sich von dem frumen heiligen convent nit scheyden, sie wern gar nit in der hell, aber wenn sy's hinauß prechten, würden sy in abgrunt der hell faren [...] wie wol sy ir mütter wern, so wern sy jn doch nit schuldig gehorsam zu sein in den dingen, die wider jr sel wern. Sprach katharina ebnerin, du pist ain mutter meines fleischs und nit meins geist, dann du hast mir mein sel nit geben, darumb pin ich dir nit schuldig gehorsam zu seyn in den dingen, die wider mein sel sein, auß dem und andern machten sy ein groß gespött, sagten, sy wollten die sach vor gott wol verantwurten und die sundt all auf sich nemen. [...] redet die katherin so dappferlich und bestendlich und beweret all jre wort mit der heiligen geschrift [...] Es hetten darnach die herren daußen gesagt, sy hetten all jr lebtag des menschen geleichen nye gehort, sye het schyr die ganze stund on unterlaß geredt, aber kein vergeben wort, sunder so wol bedechtlich, das ein jtlichs wort ein pfunt het getragen.",
         en="Da liefen die bösen Weiber herein wie die grimmigen Wölfinnen: die Fritz Tetzlin mit einer Tochter, die Hieronymus Ebnerin, die Sigmund Fürerin, unsere Pflegerin, die Kaspar Nützlin, mit ihrem Bruder Leonhard Held, der an des Pflegers Statt da war, und auch das Söhnlein des Sebald Pfinzing usw. Die Weiber hießen die Kinder mit guten Worten hinausgehen; wollten sie es aber nicht gütlich tun, so wollten sie sie mit Gewalt hinauszerren [...] Die Mütter sagten zu den Kindern, sie seien ihnen nach Gottes Gebot Gehorsam schuldig; sie wollten, dass sie hinausgingen, denn sie seien dazu da, ihre Seelen aus der Hölle zu erlösen; sie säßen dem Teufel im Rachen, das könnten sie nicht länger ohne ihr Gewissen ertragen. Die Kinder schrien, sie wollten sich vom frommen, heiligen Konvent nicht trennen, sie seien gar nicht in der Hölle; wenn man sie aber hinausbrächte, würden sie in den Abgrund der Hölle fahren [...] Obwohl sie ihre Mütter seien, seien sie ihnen doch nicht Gehorsam schuldig in den Dingen, die gegen ihre Seele seien. Katharina Ebnerin sprach: Du bist eine Mutter meines Fleisches und nicht meines Geistes, denn du hast mir meine Seele nicht gegeben; darum bin ich dir nicht schuldig, gehorsam zu sein in den Dingen, die gegen meine Seele sind. Darüber und über anderes spotteten sie sehr und sagten, sie wollten die Sache vor Gott wohl verantworten und die Sünde ganz auf sich nehmen. [...] Katharina redete so tapfer und beständig und bewies alle ihre Worte mit der Heiligen Schrift [...] Die Herren sagten danach draußen, sie hätten ihr Lebtag nicht ihresgleichen gehört; sie habe fast die ganze Stunde ohne Unterlass geredet, aber kein vergebliches Wort, sondern so wohlbedacht, dass jedes Wort ein Pfund gewogen habe.",
         note="Beide Seiten sprechen von der Hölle und vom Gewissen, und beide berufen sich auf Gottes Gebot: die Mütter auf das vierte Gebot, die Töchter auf die Pflicht, Gott mehr zu gehorchen als den Menschen. Katharinas Satz unterscheidet Mutter des Fleisches und Vater der Seele (vgl. Hebr 12,9). Leonhard Held ist der Bruder der Frau Nützel, er vertritt den Pfleger. Ausgelassen: Held hielt Clara die Hand hin, sie solle einschlagen, er nehme alle Sünden auf sich, die sie in der Welt tun werde. Das Urteil der Ratsherren über Katharina (‚jedes Wort ein Pfund‘) überliefert nur Caritas."),
    dict(n=5, titel="Die Äbtissin soll sie ledig sprechen", pg="Höfler S. 104–106", lang="fnhd",
         orig="Da schickten die herrn wider mir und clagten mir, wie sy so engstig wern [...] so wer die katherin ebnerin zumal trutzig und heftig, sy hetten mit jn gefochten das sy keinen trucken faden an jr hetten [...] paten sy mich, ich sollt sy doch der gelubd ledig sagen, ob sy villeicht mit der gehorsam verstrickt wern, das sy nit gen dorften. Sprach ich, ir habt vor von mir gehört, das ich nit gewalt hab aufzulossen was gott gelobt ist [...] Also gin ich wieder jn die cappeln hinein mit etlichen Swestern. Da stunden meine arme weißlein unter den grimmigen wolfen und strytten von allen jren kreften [...] sprach ich unter andern worten: liebe kind jr wüst, was jr gott gelobt habt, das ich nit kan auflossen [...] Aber was jr mir pisher schuldig seit gewest, will ich euch ledig sagen als vil ich soll und mag [...] Schryen die 3 kindt, als auß einem mundt: wir wöllen nit ledig gezellt sein, sunder [was] wir gott gelobt haben, wollen wir mit seiner hilf halten, wenn uns schon die wurdig mutter auspütt und aller Convent da wer, wollten wir dennoch nit auß, dann wir sind nit schuldig gehorsam zu sein wider unser professio, schreyt margaret Tezlin, o liebe mutter treibt uns nit also von euch. Sprach ich, liebe kindt, jr seht das ich euch leider nit helfen kann, dann der gewalt ist zu groß [...] ich hoff wir wollen darumb nit geschyden sein, sundern wyder zusamen kumen und ewiglich pey unserm getrewen hyrten beleyben.",
         en="Da schickten die Herren wieder zu mir und klagten mir, wie bange ihnen sei [...] die Katharina Ebnerin sei vollends trotzig und heftig, sie hätten mit ihnen gefochten, dass sie keinen trockenen Faden mehr an sich hätten [...] Sie baten mich, ich solle sie doch der Gelübde ledig sprechen, falls sie vielleicht durch den Gehorsam gebunden seien, so dass sie nicht gehen dürften. Ich sprach: Ihr habt vorher von mir gehört, dass ich keine Gewalt habe aufzulösen, was Gott gelobt ist [...] So ging ich wieder mit einigen Schwestern in die Kapelle hinein. Da standen meine armen Waislein unter den grimmigen Wölfen und stritten aus allen ihren Kräften [...] Ich sprach unter anderem: Liebe Kinder, ihr wisst, was ihr Gott gelobt habt; das kann ich nicht auflösen [...] Aber was ihr mir bisher schuldig gewesen seid, davon will ich euch ledig sprechen, so viel ich soll und kann [...] Da schrien die drei Kinder wie aus einem Mund: Wir wollen nicht ledig gesprochen sein, sondern [was] wir Gott gelobt haben, wollen wir mit seiner Hilfe halten; wenn uns auch die würdige Mutter hinausböte und der ganze Konvent dabei wäre, wollten wir doch nicht hinaus, denn wir sind nicht schuldig, gegen unsere Profess gehorsam zu sein. Margaret Tetzlin schrie: O liebe Mutter, treibt uns nicht so von Euch! Ich sprach: Liebe Kinder, ihr seht, dass ich euch leider nicht helfen kann, denn die Gewalt ist zu groß [...] Ich hoffe, wir wollen darum nicht geschieden sein, sondern wieder zusammenkommen und ewig bei unserem getreuen Hirten bleiben.",
         note="Die Ratsherren selbst kommen in Not: Sie sollen den Befehl vollziehen und wollen nicht Hand anlegen. Ihr Ausweg ist derselbe, den der Rat am 7. Juni verlangt hatte: Die Äbtissin soll die Gelübde lösen. Sie tut, was sie den Herren damals gesagt hatte: Sie entbindet die Töchter von dem, was sie ihr schulden, nicht von dem, was sie Gott gelobt haben. Die Töchter lehnen beides ab. ‚Keinen trockenen Faden‘: Die Herren waren durchgeschwitzt."),
    dict(n=6, titel="‚Da stee ich und will nicht weichen‘", pg="Höfler S. 106–107", lang="fnhd",
         orig="Sprach katherina ebnerin: da stee ich und willd nicht weichen, kein mensch sull vermugen hinauß zu gen, zeucht man mich aber mit gewalt hinauß, solls doch mein will nymer ewiglich sein, wills gott im himel und aller welt auf erden clagen. Als pald sy das gesprach, nam sy der helt unter die arm, fyng sy an zu zyechen und zerren, da lieff ich davon mit den Swestern, mocht des jamers nit sehen, etlich Swestern belieben vor der cappeln thür, die hörten das groß zanken zerren und schleppen mit großem schreyen und weynen der kinder [...] Da hub sich erst ein ungeleublich schreyen, clagen und weynen, ee sy jn den heiligen orden abrissen und jn weltliche kleyder anlegten, sy furten aber die kutten mit jn heim. Das geschrey und gefecht hörten die swester all in dem chor und auch die weltlichen leut, die vor der kirche stunden.",
         en="Katharina Ebnerin sprach: Da stehe ich und will nicht weichen; kein Mensch soll mich dazu bringen hinauszugehen. Zieht man mich aber mit Gewalt hinaus, so soll es doch nimmermehr in Ewigkeit mein Wille sein; ich will es Gott im Himmel und aller Welt auf Erden klagen. Sobald sie das gesprochen hatte, nahm sie der Held unter die Arme und fing an, sie zu ziehen und zu zerren. Da lief ich mit den Schwestern davon; ich konnte den Jammer nicht ansehen. Einige Schwestern blieben vor der Kapellentür; die hörten das große Zanken, Zerren und Schleppen mit großem Schreien und Weinen der Kinder [...] Da erhob sich erst ein unglaubliches Schreien, Klagen und Weinen, ehe sie ihnen das Ordenskleid abrissen und weltliche Kleider anlegten; die Kutten aber führten sie mit sich heim. Das Geschrei und Gefecht hörten alle Schwestern im Chor und auch die weltlichen Leute, die vor der Kirche standen.",
         note="Der Satz, der dem Modul den Titel gibt. Katharina unterscheidet, was mit ihrem Körper geschieht, von dem, was ihr Wille ist; das ist die Rechtsform eines Protests, wie ihn die Äbtissin im März vor den Gesandten erklärt hatte (Modul ‚Die Väter genommen‘). Was folgte, sah Caritas nicht: Sie ging hinaus und gibt wieder, was die Schwestern vor der Tür hörten. Ausgelassen ist die Schilderung des Hinausschleppens im Einzelnen. Die Mütter nahmen die Kutten mit; die Töchter sollten sie nicht wiederhaben."),
    dict(n=7, titel="Vor der Kirche und vor dem Vaterhaus", pg="Höfler S. 107", lang="fnhd",
         orig="Da man sy nun auf die wegen wollt setzen vor der kirchen wurd aber großer jamer, rufften die armen kint mit lauter stym zu den leuten und clagten jn, sy lyden gewalt und unrecht, das man sy mit gewalt aus dem closter gezogen het. Die clara Nuzlin het laut gesprochen O du schöne mutter gottes, du weyst das es mein will nit ist. Da man sy nun hinfuret, warn ytlichen yr kamerwagen vil hundert puben und ander leut nachgeloffen [...] Da nun ytlicher wagen fur jrs vaters haus war kumen, het sy ein news schreyen und laut's weynen angehabt, das die leut groß mitleiden mit jr hetten gehabt, auch landsknecht, die mit jn geloffen warn, hetten gesagt wenn sy nit eins auflaufs besorgten und die stadtknecht die auch da warn, so wollten sy mit dem schwert darein geschlagen haben und den armen kind geholffen. Vor des ebners thur am Obsmark war das ketterlein abgestygen, hett die hent ob dem kopf zusammen geschlagen und aber mit großen weynen den leuten geklagt, wie jm gewalt und unrecht gescheen wider seinen willen, das die öbserin schyr all mit jm geweint hetten.",
         en="Als man sie nun vor der Kirche auf die Wagen setzen wollte, gab es wieder großen Jammer. Die armen Kinder riefen mit lauter Stimme zu den Leuten und klagten ihnen, sie litten Gewalt und Unrecht, dass man sie mit Gewalt aus dem Kloster gezogen habe. Clara Nützlin sprach laut: O du schöne Mutter Gottes, du weißt, dass es nicht mein Wille ist. Als man sie nun fortfuhr, liefen jedem Kammerwagen viele hundert Buben und andere Leute nach [...] Als dann jeder Wagen vor das Haus ihres Vaters gekommen war, hob sie ein neues Schreien und lautes Weinen an, so dass die Leute großes Mitleid mit ihr hatten; auch Landsknechte, die mitgelaufen waren, sollen gesagt haben, wenn sie nicht einen Aufruhr und die Stadtknechte, die auch dabei waren, fürchteten, so hätten sie mit dem Schwert dreingeschlagen und dem armen Kind geholfen. Vor Ebners Tür am Obstmarkt stieg das Käthchen ab, schlug die Hände über dem Kopf zusammen und klagte wieder mit großem Weinen den Leuten, wie ihm Gewalt und Unrecht gegen seinen Willen geschehen sei, so dass die Obstfrauen fast alle mit ihm geweint haben sollen.",
         note="Was auf dem Weg geschah, kennt Caritas nur vom Hörensagen (‚het … gesprochen‘, ‚hetten gesagt‘: Konjunktiv des Berichts). Ausgelassen ist eine Nachricht, die Mutter Ebner habe Katharina auf dem Wagen ins Gesicht geschlagen; sie steht bei Höfler S. 107. Die Töchter klagen öffentlich, ‚sie litten Gewalt und Unrecht‘: Ihr Protest geht an die Stadt, nicht an den Rat. Das Haus der Ebner lag am Obstmarkt (Tafel)."),
]

DANACH = [
    dict(n=1, titel="Am vierten Tag; das Inventar, die Kutten, das Fenster", pg="Höfler S. 108–109", lang="fnhd",
         orig="Wie es den armen kindern unter den grimmigen wolfen darnach weiter ist gangen, kunen wir nit wissen, denn das man uns am fyrten tag darnach saget, die clara Nuzlin het noch keinen pissen in der welt geessen, weyneten die andern on alls aufhören. Sy haben ye allen jrn fleyß gethun, des gib ich jn gezeugtnus vor gott und den menschen, so haben sy dem Convent nye nichcz poß nachgeredt [...] Got helf uns wider mit frewden zusamen [...] Darnach machten wir das Inventarium, als man uns von Rats wegen gepotten het. Aber von den gnaden gottes hat man es noch nit geholt. Mit den kleydern hielten wir auch still, schnitten nichcz noch ließen auch nichcz ferben wye andere closter, do kom es den leuten ein wenig auß dem synn [...] Das gesychtfenster müsten wir leyder lassen machen, theten wir erst auf den nechsten tag vor dem endt der 4 Wochen [...] aber von den genaden gottes hat sich kein swester lassen bewegen, wollten auch dye swestern nit allein mit jrn freunten reden, denn sy besorgten man wurd jn jr ret verkeren, wenn nymant da wer, der zuhöret. [...] Wer einmal da was, kom nit pald herwider. laus Deo.",
         en="Wie es den armen Kindern unter den grimmigen Wölfen danach weiter ergangen ist, können wir nicht wissen, nur dass man uns am vierten Tag danach sagte, Clara Nützlin habe noch keinen Bissen in der Welt gegessen, und die anderen weinten ohne Aufhören. Sie haben ja allen Fleiß getan, das bezeuge ich ihnen vor Gott und den Menschen, und sie haben dem Konvent nie etwas Böses nachgesagt [...] Gott helfe uns, dass wir mit Freuden wieder zusammenkommen [...] Danach machten wir das Inventar, wie man es uns von Rats wegen geboten hatte; aber durch Gottes Gnade hat man es noch nicht geholt. Mit den Kleidern hielten wir still, schnitten nichts und ließen auch nichts färben wie andere Klöster; da kam es den Leuten ein wenig aus dem Sinn [...] Das Gesichtsfenster mussten wir leider machen lassen; wir taten es erst am letzten Tag vor dem Ende der vier Wochen [...] Aber durch Gottes Gnade hat sich keine Schwester bewegen lassen, und die Schwestern wollten auch nicht allein mit ihren Verwandten reden, denn sie fürchteten, man würde ihnen ihre Rede verdrehen, wenn niemand dabei wäre, der zuhörte. [...] Wer einmal da war, kam nicht so bald wieder. Gott sei Lob.",
         note="Die Bilanz der fünf Artikel nach vier Wochen: Inventar gemacht, aber nicht abgeholt; Kutten behalten; Gesichtsfenster gebaut, am letzten Tag der Frist; Gelübde nicht gelöst. Die Töchter waren draußen. Was aus Katharina Ebner, Clara Nützel und Margaretha Tetzel später wurde, sagen die Denkwürdigkeiten an dieser Stelle nicht."),
    dict(n=2, titel="August 1525: das Kostgeld und der ‚Kirchenraub‘", pg="Höfler S. 109–111", lang="fnhd",
         orig="Darnach am suntag nach S. Lorenzentag kom herr sygmundt furer und linhart Tucher, foderten mich an das gesichtfenster, wie sie von herr Jeronimus Ebner, Caspar Nutzel und Friderich Tezlin zu geschickt wern [...] wollten sy uns gern vmb solchs ein widerlegung thun, begerten nit, das wir sy die langen jar vmbsunst gehalten hetten, ich sollt jn ein summa bestymen, die wollten sy gern nach jrm vermugen ausrichten für das kostgelt. Sagt ich jn, es wer nit not [...] aber wie dem allem wollt ich nichcz fodern, denn ein ding, wenn sy mir den kirchenraub widergeben, den sie uns mit gewalt genummen hetten an den 3 kindern die sy uns mit gewalt wider jrn willen geraubt hetten, so wollt ich sy quittiren alles kostgelts. Sprach der furer, warumb wir sy wider ein wollten nemen, er hett uns doch vorgeraten das wir keine wider ein sollten nemen die von uns kemen. Sprach ich das wöllen wir thun, welche mit willen von uns lauft und nit getraut pey uns selig zu werden, die wöllen wir nymer mer wider einnemen, aber es ist wissenlich mit was jamers weynen und clagen diße 3 kindt mit gewalt wider jrn willen von uns genumen sind worden, darumb wollen wir sy gern wider aufnemen welche stund sy kumen. Sagten sy [...] sy gelaubten, wenn es an den kindten lege, sy kemen alle 3 noch vor nacht wider zu uns, aber sy gedechten wol jr eltern würden des nymer mer gestatten [...] Sagt ich, dieweil ich am ampt wer gewest het ich von nymant kein kostgelt oder anders gefodert [...] het man uns etwas geben, hetten wir gott gedankt, hett man uns nichcz geben hetten wir uns nit gezankt.",
         en="Danach, am Sonntag nach dem Laurentiustag, kamen Herr Sigmund Fürer und Leonhard Tucher und riefen mich an das Gesichtsfenster: Sie seien von Herrn Hieronymus Ebner, Kaspar Nützel und Friedrich Tetzlin geschickt [...] sie wollten uns dafür gern eine Entschädigung leisten und nicht verlangen, dass wir sie die langen Jahre umsonst gehalten hätten; ich solle ihnen eine Summe nennen, die wollten sie gern nach ihrem Vermögen für das Kostgeld bezahlen. Ich sagte ihnen, das sei nicht nötig [...] Wie dem aber auch sei, ich wolle nichts fordern als eines: Wenn sie mir den Kirchenraub zurückgäben, den sie uns mit Gewalt genommen hätten an den drei Kindern, die sie uns mit Gewalt gegen ihren Willen geraubt hätten, so wolle ich sie alles Kostgelds quitt sprechen. Der Fürer sprach, warum wir sie wieder aufnehmen wollten, er habe uns doch vorher geraten, keine wieder aufzunehmen, die von uns ginge. Ich sprach: Das wollen wir tun; welche mit Willen von uns läuft und nicht darauf vertraut, bei uns selig zu werden, die wollen wir nie mehr wieder aufnehmen. Aber es ist bekannt, mit was für Jammer, Weinen und Klagen diese drei Kinder mit Gewalt gegen ihren Willen von uns genommen worden sind; darum wollen wir sie gern wieder aufnehmen, zu welcher Stunde sie kommen. Sie sagten [...] sie glaubten, wenn es an den Kindern läge, kämen alle drei noch vor der Nacht wieder zu uns; aber sie dächten wohl, ihre Eltern würden das nie mehr gestatten [...] Ich sagte: Solange ich im Amt gewesen sei, hätte ich von niemandem Kostgeld oder anderes gefordert [...] Hätte man uns etwas gegeben, hätten wir Gott gedankt; hätte man uns nichts gegeben, hätten wir uns nicht gezankt.",
         note="Sonntag nach Laurentius (10. August) war 1525 der 13. August. Die Väter bieten Kostgeld für die Jahre im Kloster an; die Äbtissin verlangt stattdessen die Töchter zurück und nennt ihre Wegnahme ‚Kirchenraub‘. Im Februar hatte der Konvent erklärt, wer einmal draußen sei, komme nicht wieder herein (Modul ‚Verhört man doch einen Dieb‘); jetzt unterscheidet Caritas: Wer freiwillig geht, nicht; wer mit Gewalt genommen wurde, jederzeit. Die Gesandten selbst geben zu, die drei kämen ‚noch vor der Nacht‘ zurück, wenn es an ihnen läge. Caritas vermerkt, dass man ihr ‚weder Heller noch Pfennig‘ gab (ausgelassen)."),
    dict(n=3, titel="Wie der Stadtschreiber es erzählte: ‚des Klosterlebens überdrüssig‘", pg="Höfler S. 107–108, Anm.",
         en="Genügt Ein Beweis, wie die Reformationsgeschichten geschrieben wurden, so ist es, wie sich der officielle Geschichtschreiber der Stadt Nürnberg, Millner, in seinen Relationen über diese arge Beeinträchtigung der Gewissen ausdrückt: „es seyn auch etlich closterfrawen in der Stadt des closterlebens überdrüßlich geworden, dann Hieronymus Ebner's, Caspar Nüzels und Friederich Tezels Töchter haben die Ordenskleider abgelegt und sich aus dem Clara Closter wieder zu ihren Eltern begeben.“ Schade daß er nicht geradezu sagte, sie seyen ausgetreten; dieser freywillige Act, wie er ihn hinstellt, hätte vortrefflich gepaßt zu der oben erwähnten Thatsache, daß man dem einen armen Mädchen beinahe den Fuß abgetreten hat, als es „sich wieder zu seinen Eltern begab.“",
         note="Eine Anmerkung des Herausgebers Constantin Höfler von 1852, im deutschen Original. Sie zitiert die Nürnberger Stadtchronik von Johannes Müllner (‚Millner‘), dem Ratsschreiber des frühen 17. Jahrhunderts, nach der neueren Literatur abgeschlossen um 1623; den Wortlaut bei Müllner hat dieser Apparat nicht geprüft. Zwei Fassungen desselben Tages: Bei Müllner legten die Töchter die Ordenskleider ab ‚und begaben sich zu ihren Eltern‘, aus Überdruss; bei Caritas wurden sie hinausgetragen. Höflers Ironie ist die Stimme eines katholischen Historikers von 1852 und selbst parteiisch; die Gegenüberstellung der Quellen trägt auch ohne sie."),
]

doc = {
    "id": "toechter",
    "titel": "Da stee ich: die Töchter, Juni 1525",
    "autor": "Caritas Pirckheimer; dazu Constantin Höfler (1852) über Johannes Müllner",
    "jahr": "10. bis 14. Juni 1525; August 1525",
    "sprache": "de",
    "orig_sprache": "fnhd",
    "pg_label": "",
    "quelle": "C. Höfler (Hg.), Der hochberühmten Charitas Pirkheimer, Aebtissin von S. Clara zu Nürnberg, Denkwürdigkeiten aus dem Reformationszeitalter (Quellensammlung für fränkische Geschichte 4, Bamberg 1852), S. 97–111 (Internet Archive: 11420769bsb). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Der frühneuhochdeutsche Text ist am Seitenbild gelesen. Höflers erklärende Zusätze in runden Klammern sind weggelassen, Ergänzungen stehen in eckigen Klammern, ‚&c.‘ steht für ‚ꝛc.‘. Auslassungen sind mit [...] bezeichnet; ausgelassen sind auch einige Einzelheiten der Gewalt, die die Anmerkungen nennen. Caritas' Wörter für die Mütter (‚böse Weiber‘, ‚grimmige Wölfinnen‘) stehen, wie sie sie schrieb; sie sind ihr Urteil. Die Übersetzung ist eigene Arbeit (CC0).",
    "sections": [
        {"id": "vorher", "autor": "Caritas Pirckheimer", "titel": "Drei Tage vorher, 10. bis 13. Juni", "zk": "Vorher",
         "plates": ["obstmarkt1725"],
         "blurb": "Die Väter Ebner und Nützel lassen ihren Töchtern ausrichten, man werde sie holen. Am Montag stehen vier Mütter vor dem Kloster und wollen hinein; das Gespräch allein am Fenster lehnen sie ab. Am Dienstag verklagen sie die Äbtissin vor dem Rat, und der Rat befiehlt, die Töchter herauszugeben, ‚es sei den Kindern lieb oder leid‘.",
         "units": VORHER},
        {"id": "fronleichnam", "autor": "Caritas Pirckheimer", "titel": "Der Vorabend von Fronleichnam, 14. Juni", "zk": "Fronleichnam",
         "plates": ["hoefler_s104", "hoefler_s106"],
         "viz": "drei",
         "blurb": "Margaretha Tetzel, Katharina Ebner und Clara Nützel, 23, 20 und 19 Jahre alt, werden in der Klosterkapelle den Müttern übergeben, vor zwei Ratsherren und mit einer Menge auf dem Kirchhof. Die Äbtissin will sie nicht heimlich hinausgeben und nicht selbst hinausschicken. Katharina: ‚Du bist eine Mutter meines Fleisches und nicht meines Geistes‘ und ‚Da stehe ich und will nicht weichen‘.",
         "units": FRONLEICHNAM},
        {"id": "danach", "autor": "Caritas Pirckheimer; Constantin Höfler", "titel": "Danach", "zk": "Danach",
         "plates": ["hoefler_s107"],
         "blurb": "Was die Schwestern von den dreien noch hörten, wie der Konvent die übrigen Artikel erfüllte und nicht erfüllte, und wie die Väter im August Kostgeld anboten und die Äbtissin die Töchter zurückverlangte. Am Ende, wie der Nürnberger Stadtchronist den Tag erzählte: die Töchter seien ‚des Klosterlebens überdrüssig‘ geworden.",
         "units": DANACH},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("toechter.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
