"""Modul: Luther und die Nonnen, 1523 und 1526.
Schreibt data/vergleich.json.

Quellen, am Seitenbild gelesen:
- M. Luther, Ursach und Antwort, daß Jungfrauen Klöster göttlich verlassen
  mögen (1523), in: D. Martin Luthers Werke, Kritische Gesamtausgabe, Bd. 11
  (Weimar 1900), S. 394-400 (Internet Archive werkekritischege11luthuoft,
  Blatt = S.+57); Einleitung S. 387-389.
- Herzog Georg von Sachsen, Instruktion für Otto Pack, 1526, nach
  C. Höfler, Denkwürdigkeiten der Charitas Pirkheimer (Bamberg 1852),
  Einleitung S. LXII-LXV (Internet Archive 11420769bsb, Blatt n68-n71).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "vergleich.json"

URSACH = [
    dict(n=1, titel="‚Ja freilich ein seliger Räuber‘", pg="WA 11, S. 394–395", lang="fnhd",
         orig="Dem fursichtigen und weyßen Leonhard Koppen, Burger zu Torgaw, meynem besondern freunde, Gnad und frid Martinus Luther.\n\nGnad und frid ynn Christo. Es ist freylich also wie die schrifft sagt, das niemant kan frumen odder schaden thun, er sey denn datzu verordenet von Gott [...] Mocht yhr sagen: Wo will das hynaus? Dahyn aus, das yhr eyn new werck gethan habt, davon land und leuth singen und sagen werden, wilchs viel werden fur grossen schaden aus schreyen. Aber die es mit Gott hallten, werdens fur grossen frumen preyssen, auff das yhr gewiß seyt, das es Gott alßo verordeneth hatt und nicht ewer eygens werck nach radt ist, unnd gehen lasßet der ienigen geschrey, die es fur das aller ergist werck thaddeln werden und von Gott widder verordenet noch befolhen achten. Pfw, Pfw, werden sie sagen, Der narr Leonhard Koppen hatt sich den verdampten ketzrisschen Monch lassen fangen und feret zu und furet neun Nonnen auff eyn mal aus dem kloster und hilfft yhn yhr gelubd und klosterlich leben zu verleucken und zu verlassen.\n\nHie werdet yhr aber mal sagen: Das ist warlich heymlich gehallten und wol verporgen, ja verrhaten und verkaufft, das auff mich erhetzet werde das gantze kloster zu Nymptzschen, weyl sie nu horen, das ich der reuber geweßen byn. Antwortt ich: ja freylich eyn seliger reuber, gleych wie Christus eyn reuber war ynn der wellt, da er durch seynen todt dem Fursten der wellt seynen harnsch und haus geredt nam und furt yhn gefangen. Also habt yhr auch diße armen seelen aus dem gefengnis menschlicher tyranney gefurt eben umb die rechten zeyt auff die ostern, da Christus auch der seynen gefengnis gefangen nam.",
         en="Dem vorsichtigen und weisen Leonhard Koppe, Bürger zu Torgau, meinem besonderen Freund, Gnade und Frieden, Martin Luther.\n\nGnade und Frieden in Christus. Es ist freilich so, wie die Schrift sagt, dass niemand Nutzen oder Schaden tun kann, er sei denn von Gott dazu verordnet [...] Ihr möchtet sagen: Worauf soll das hinaus? Darauf, dass Ihr ein neues Werk getan habt, von dem Land und Leute singen und sagen werden, und viele werden es als großen Schaden ausschreien. Aber die es mit Gott halten, werden es als großen Nutzen preisen; damit Ihr gewiss seid, dass Gott es so verordnet hat und es nicht Euer eigenes Werk oder Euer eigener Rat ist, und das Geschrei derer gehen lasst, die es als das allerärgste Werk tadeln und es weder für von Gott verordnet noch befohlen halten werden. Pfui, pfui, werden sie sagen, der Narr Leonhard Koppe hat sich von dem verdammten ketzerischen Mönch fangen lassen, fährt zu und führt neun Nonnen auf einmal aus dem Kloster und hilft ihnen, ihr Gelübde und Klosterleben zu verleugnen und zu verlassen.\n\nHier werdet Ihr wieder sagen: Das ist wahrlich heimlich gehalten und gut verborgen, ja verraten und verkauft, damit das ganze Kloster zu Nimbschen gegen mich aufgehetzt werde, weil sie nun hören, dass ich der Räuber gewesen bin. Ich antworte: Ja freilich, ein seliger Räuber, so wie Christus ein Räuber in der Welt war, als er durch seinen Tod dem Fürsten der Welt seinen Harnisch und seinen Hausrat nahm und ihn gefangen führte. So habt auch Ihr diese armen Seelen aus dem Gefängnis menschlicher Tyrannei geführt, gerade zur rechten Zeit, um Ostern, als auch Christus das Gefängnis der Seinen gefangen nahm.",
         note="Nach der Einleitung der Weimarer Ausgabe (S. 387–388) befreiten der Torgauer Bürger Leonhard Koppe, dessen Vetter und Wolf von Dommitzsch am 4. April 1523, dem Samstag vor Ostern, zwölf Zisterzienserinnen aus dem Kloster Marienthron in Nimbschen bei Grimma. Drei gingen zu Verwandten in Kursachsen; die anderen konnten nicht zu ihren Familien, deren Güter im Herzogtum Sachsen lagen, weil ‚Herzog Georgs Rache‘ zu fürchten war (Abschnitt ‚Herzog Georg‘), und kamen am 7. April nach Wittenberg. Luther lässt Koppe sagen, das Unternehmen sei verraten, und antwortet selbst: Er war der ‚Räuber‘, also der Anstifter. Wie die Frauen aus dem Kloster kamen, erzählt der Brief nicht. ‚Pfw‘ ist ‚pfui‘."),
    dict(n=2, titel="Nicht heimlich, nicht einzeln", pg="WA 11, S. 395", lang="fnhd",
         orig="Das ich aber solchs aus ruffe und nicht heymlich hallte, thu ich aus redlichen ursachen. Erstlich, das es nicht darumb ist durch mich angeregt, das es sollt heymlich bleyben. Denn was wyr thun, das thun wir in gott und schewen uns des nicht am liecht. Wollt Gott, ich kund auff solche odder andere weyße alle gefangene gewissen erredten und alle kloster ledig machen. Ich wollt michs darnach nichts schewen zu bekennen sampt allen, die da zu geholffen hetten, trostlicher zuversicht, Christus, der nu widder hatt seyn Euangelion an tag gebracht und des Endechrists reich storet, wurde hye schutz herr seyn, obs auch das leben kosten muste.\n\nCzum andern thu ichs, der armen kinder und yhrer freundschafft ehre zu erhallten. Denn wie hoch die blinden frevel richter solchs auff erden fur ketzerey und abtrinnigkeyt schellten (wilchs seyn richter wol finden wirt), so haben wyr doch das verwaret, das niemant sagen thar, sie seyen durch loße buben unredlich ausgefurt und yhrer ehre ynn fahr sich begeben, Die weyl man euch und die ewren kan antzeygen. Datzu mus das yderman lassen erbarlich gehandelt seyn, das sie nicht eyntzelen, eyne hie hynaus, die andern dahynaus geloffen sind, sondern allesampt beyeynander mit aller zucht und ehre an redliche stett und ortte komen, da mit den lester meulern die ursach genomen werde, yhr lugenhafftige zungen mit frumen kindern zu wasschen. Denn das sie solchs widder Gott und yhr gelubdt gethan schellten, wollen wyr leyden und wagen.",
         en="Dass ich aber so etwas ausrufe und nicht geheim halte, tue ich aus redlichen Gründen. Erstens, weil es nicht darum von mir angeregt worden ist, dass es geheim bleiben sollte. Denn was wir tun, das tun wir in Gott und scheuen uns damit nicht vor dem Licht. Wollte Gott, ich könnte auf diese oder andere Weise alle gefangenen Gewissen erretten und alle Klöster leer machen. Ich wollte mich danach nicht scheuen, es zu bekennen, mitsamt allen, die dazu geholfen hätten, in der tröstlichen Zuversicht, Christus, der sein Evangelium nun wieder ans Licht gebracht hat und das Reich des Antichrists zerstört, würde hier Schutzherr sein, und wenn es auch das Leben kosten müsste.\n\nZweitens tue ich es, um die Ehre der armen Kinder und ihrer Verwandtschaft zu erhalten. Denn wie sehr die blinden, frevelhaften Richter auf Erden das als Ketzerei und Abtrünnigkeit schelten mögen (ihren Richter werden sie wohl finden), so haben wir doch dafür gesorgt, dass niemand zu sagen wagt, sie seien von losen Buben unredlich entführt worden und hätten ihre Ehre in Gefahr gebracht, weil man Euch und die Euren nennen kann. Dazu muss jedermann gelten lassen, dass ehrbar gehandelt worden ist, dass sie nicht einzeln, eine hier hinaus, die andere dort hinaus, gelaufen sind, sondern alle beieinander mit aller Zucht und Ehre an redliche Stätten und Orte gekommen sind, damit den Lästermäulern der Anlass genommen werde, ihre lügenhaften Zungen an frommen Kindern zu waschen. Dass sie es aber schelten, das sei gegen Gott und gegen ihr Gelübde getan, das wollen wir leiden und wagen.",
         note="Der Brief ist von vornherein für den Druck geschrieben, wie die Weimarer Ausgabe bemerkt (S. 388): Die Namen am Schluss kannte Koppe ohnehin. Die Sorge um die Ehre ist dieselbe wie in Nürnberg, nur andersherum: Caritas gab die drei Töchter 1525 ‚nicht heimlich‘ durch die Kirchentür hinaus (Modul ‚Da stee ich‘, Fronleichnam [3]), und der Konvent fürchtete das ‚Hinaus- und Hineinlaufen‘ (Modul ‚Verhört man doch einen Dieb‘, Klage [5])."),
    dict(n=3, titel="Den Adel warnen, die Bahn zu brechen", pg="WA 11, S. 395", lang="fnhd",
         orig="Czum dritten, zu warnen die hern vom Adel und alle frume bidder leutte, so kinder ynn klostern haben, das sie selbs datzu thun und sie erausser nemen, auff das nicht ergers hernach folge. Denn wie wol viel des adels und bidder leutte der sachen von gottis gnaden verstendig yhre kinder odder freundyn wol gernn eraus hetten und doch das exempel schewen, die ersten ban zu brechen, Nu aber sie sehen, das so viel erbarer kinder mit verwarter zucht und ehre die ban gebrochen haben und des bekentlich sind, werden sie mutiger und thurstiger werden. Werden aber ettliche zorniger, das mus man lassen geschehen und sich nicht verwundern. Denn sie dencken, es sey unrecht, nach dem sie bißher verfurt nicht anders geleret sind. Es wirt mit der zeyt besser werden.",
         en="Drittens, um die Herren vom Adel und alle frommen, biederen Leute, die Kinder in Klöstern haben, zu mahnen, dass sie selbst dazu tun und sie herausnehmen, damit nicht Ärgeres danach folge. Denn obwohl viele vom Adel und biedere Leute, die die Sache durch Gottes Gnade verstehen, ihre Kinder oder Verwandten gern heraus hätten und doch das Beispiel scheuen, als Erste die Bahn zu brechen: Wenn sie nun sehen, dass so viele ehrbare Kinder mit bewahrter Zucht und Ehre die Bahn gebrochen haben und sich dazu bekennen, werden sie mutiger und kühner werden. Werden aber einige zorniger, so muss man das geschehen lassen und sich nicht wundern. Denn sie denken, es sei unrecht, weil sie bisher verführt und nicht anders gelehrt worden sind. Es wird mit der Zeit besser werden.",
         note="Was Luther hier den Eltern empfiehlt, taten zwei Jahre später drei Nürnberger Ratsfamilien, die Ebner, Nützel und Tetzel: Sie holten ihre Töchter selbst heraus, gegen deren Willen (Modul ‚Da stee ich‘). Ob sie sich auf diese Schrift beriefen, sagen die Quellen dieses Apparats nicht."),
    dict(n=4, titel="‚Aufs allerdemütigste gebeten‘", pg="WA 11, S. 396", lang="fnhd",
         orig="[...] Auff das ich aber auch unser aller wortt rede, beyde meyns, der ichs geraten und gebeten, und ewer mit den ewern, die yhrs aus gericht, und der jungfrawen, die der erlosunge bedurfft haben, Will ich hie mit kurtzlich fur Gott und aller wellt rechenschafft und anttwort geben [...]\n\nAuffs erst, das die kinder zuvorn selbs yhr Eldern und freundschafft auffs aller demutigst ersucht und gebeten haben umb hulff, eraus zu komen, mit vernunfftigen gnugsamen ursachen angetzeygt, das yhnen solch leben der seelen selickeyt halben nicht lenger zu dulden sey, sich daneben erbotten, zu thun und zu leyden, was frum kinder thun und leyden sollen. Wilchs yhn alles abgeschlagen und versagt ist und also von yderman verlassen sind, damit sie recht und redlich ursach gehabt, ja genottigt und gedrungen sind, yhr gewissen und seele zu erredten, anderswo, wie sie haben kunden, hulff und radt suchen. Und die ihenigen, so hie haben kunden helffen und radten, schuldig geweßen sind, aus Christlicher liebe pflicht, die seelen und gewissen zu erredten.",
         en="[...] Damit ich aber für uns alle spreche, für mich, der ich es geraten und erbeten habe, für Euch mit den Euren, die es ausgeführt haben, und für die Jungfrauen, die der Erlösung bedurften, will ich hiermit kurz vor Gott und aller Welt Rechenschaft und Antwort geben [...]\n\nErstens: Die Kinder haben zuvor selbst ihre Eltern und Verwandtschaft aufs allerdemütigste ersucht und um Hilfe gebeten, herauszukommen, und mit vernünftigen, hinreichenden Gründen dargelegt, dass ihnen ein solches Leben um ihres Seelenheils willen nicht länger zu ertragen sei; daneben haben sie sich erboten, zu tun und zu leiden, was fromme Kinder tun und leiden sollen. Das alles ist ihnen abgeschlagen und versagt worden, und so sind sie von jedermann verlassen; damit haben sie rechten und redlichen Grund gehabt, ja sind genötigt und gedrungen gewesen, ihr Gewissen und ihre Seele zu retten und anderswo, wie sie konnten, Hilfe und Rat zu suchen. Und die, die hier helfen und raten konnten, waren aus Pflicht christlicher Liebe schuldig, die Seelen und Gewissen zu retten.",
         note="Der Kern des Briefes: Die Frauen wollten hinaus, die Familien verweigerten es. In Nürnberg 1525 war es umgekehrt: Die Mütter wollten die Töchter heraus, die Töchter wollten bleiben, und Katharina Ebner sagte zu ihrer Mutter, sie sei ‚eine Mutter meines Fleisches und nicht meines Geistes‘ (Modul ‚Da stee ich‘, Fronleichnam [4]). Beide Seiten berufen sich auf das Gewissen der Tochter gegen den Willen der Eltern. Luther selbst ‚hat es geraten und erbeten‘: Er übernimmt die Verantwortung."),
    dict(n=5, titel="Wo Gottes Wort nicht täglich geht", pg="WA 11, S. 396–397", lang="fnhd",
         orig="Czum andern ist das eyn hohe wichtige ursach und nott, das man leyder die kinder, sonderlich das schwache weyber volck und junge megde ynn die kloster stosset, reytzt und gehen lest, da doch keyn teglich ubung ist gotlichs wortts, ja sellten odder nymer mehr das Euangelion eyn mal recht gehorett wirt. Und werden doch ynn den hohisten kampff gestellet: Nemlich umb die jungfrawschafft zu streytten, da kaumet und gar selten auch die ihenigen bestehen, die mit gottis wort allenthalben gerust und mit hoher seltzamer wunderbarlicher gnad erhaben sind. [...] O der unbarmhertzigen eldern und freunden, die mit den yhren so grewlich und schrecklich faren, O der blinden und tollen Bisschoff und Ebten, die hie nicht sehen noch fulen, was dye armen seelen leyden und wie sie verterben.\n\nDiße ursach, das man Gottis wort mangeln mus, ist alleyne gnug, ob sonst keyn andere were, uns alle zu entschuldigen, ja zu loben und zu preyssen fur Gott und der wellt, das man aus klostern lauffen helffen und ratten soll, das die seelen eraus geryssen, gefurt, gestolen und geraubt werden, wie man kan, unangesehen, ob tausent eyd und gelubd geschehen weren. Denn wissentlich ists, das ynn klostern, sonderlich nonnen klostern Gottis wort teglich nicht gehet und am meysten ortten nymer mehr, sondern sich nur blewen und treyben mit menschen gesetzen und wercken. So ists widderumb gewiß, das man on gottis wort teglich fur gott nicht leben kan. Und keyn gelubt fur Gott gellten odder halten kan, da mit man sich an den ortt verbindet, da keyn gottis wortt gehet, und den ortt lest, da gottis wort gehet.",
         en="Zweitens ist das ein hoher, wichtiger Grund und eine Not, dass man leider die Kinder, besonders das schwache Frauenvolk und junge Mädchen, in die Klöster stößt, lockt und gehen lässt, wo doch keine tägliche Übung im Wort Gottes ist, ja selten oder nie das Evangelium einmal recht gehört wird. Und doch werden sie in den höchsten Kampf gestellt, nämlich um die Jungfräulichkeit zu streiten, in dem kaum und gar selten auch die bestehen, die überall mit Gottes Wort gerüstet und durch hohe, seltene, wunderbare Gnade erhoben sind. [...] O der unbarmherzigen Eltern und Verwandten, die mit den Ihren so grausam und schrecklich verfahren! O der blinden und tollen Bischöfe und Äbte, die hier nicht sehen noch fühlen, was die armen Seelen leiden und wie sie verderben!\n\nDieser Grund, dass man Gottes Wort entbehren muss, ist allein genug, auch wenn es keinen anderen gäbe, uns alle zu entschuldigen, ja zu loben und zu preisen vor Gott und der Welt dafür, dass man helfen und raten soll, aus Klöstern zu laufen, dass die Seelen herausgerissen, geführt, gestohlen und geraubt werden, wie man kann, ungeachtet, ob tausend Eide und Gelübde geschehen wären. Denn bekanntlich geht in den Klöstern, besonders in den Nonnenklöstern, Gottes Wort nicht täglich und an den meisten Orten nie, sondern man plagt und treibt sich nur mit Menschensatzungen und Werken. Ebenso gewiss ist, dass man ohne Gottes Wort nicht täglich vor Gott leben kann. Und kein Gelübde kann vor Gott gelten oder halten, mit dem man sich an den Ort bindet, wo kein Wort Gottes geht, und den Ort verlässt, wo Gottes Wort geht.",
         note="Luthers allgemeine Behauptung über ‚die Klöster‘ ist Polemik, kein Befund. Für das Nürnberger Klarakloster schrieb der Konvent Ende 1524 an den Rat, die Schwestern hätten das Alte und Neue Testament ‚deutsch und lateinisch im täglichen Gebrauch‘ (Modul ‚Die große Sündflut‘, Bittschrift [3]). Und doch sagte Anna Schwarz 1528 zu ihrer Mutter, ‚man halte das Evangelium bei uns nicht‘ (Modul ‚Visitiert und verlassen‘, Anna [3]): Was ‚Gottes Wort‘ hieß, war gerade der Streitpunkt. ‚Herausgerissen, gestohlen und geraubt, wie man kann‘ ist Luthers Wort; Caritas nannte das, was ihr 1525 geschah, mit demselben Wort: die drei Töchter seien dem Konvent ‚mit Gewalt gegen ihren Willen geraubt‘ worden (Modul ‚Da stee ich‘, Danach [2])."),
    dict(n=6, titel="‚Unter tausend kaum eine‘", pg="WA 11, S. 397", lang="fnhd",
         orig="Auffs dritte ist das kundlich und offinbar, das eyn mensch mag wol getzwungen werden fur der wellt zu thun, das er nicht gerne thut. Aber fur Gott und ynn Gottis dienst soll und kan keyn werck noch dienst getzwungen und ungerne geschehen. Denn Gotte gefallen nicht und will auch nicht haben getzwungene unwillige dienste, Wie S. Paulus 2. Corin. 9. sagt ‚Gott hatt lieb ein frolichen geber‘, on zweyffel ist er widderumb feynd eym unfrolichen unwilligen geber. Daher auch S. Paulus die edle jungfrawschafft nicht haben will, wo sie ertzwungen und unwillig geschicht 1. Corin. 7. Solche froliche lust aber zu gottis dienst gibt widder kloster noch kappen, widder gelubd noch werck, sondern alleyn der heylige geyst.\n\nWie viel meynstu aber, das Nonnen ynn klostern sind, da das teglich gottis wort nicht gehet, die frolich und mit lust ungetzwungen yhren gottes dienst thu und orden trage? freylich unter thausent kaum eyne. Was ists denn, das du solchs kind lessist also seyn leben und alle seyne werck verlieren und datzu die helle da mit verdienen? Were es nicht besser, wenn sie ja etwas ungerne und mit unlust thun soll, sie were ehlich und thet solche muhe und unlust ym ehlichen standt euserlich gegen die menschen, als yhr man, kind, gesind und nachbar &c.? Weyl denn Gott keyn dienst gefellt, es gehe denn willig von hertzen und mit lust, So folget, das auch keyn gelubd weytter gellten noch geschehen noch gehallten werden soll, denn so fern die lieb und lust da ist, das ist, so fern der heylige geyst da ist. Darumb, nun solch gelubt on lust und geist geschicht, achtets got nicht und nympts nicht an, Das also dis auch eyn gnugsame ursach ist, gelubd und kloster zu lassen und yderman eraus zu helffen ynn eynen andern standt.",
         en="Drittens ist das bekannt und offenbar, dass ein Mensch vor der Welt wohl gezwungen werden kann, zu tun, was er nicht gern tut. Aber vor Gott und in Gottes Dienst soll und kann kein Werk und kein Dienst erzwungen und ungern geschehen. Denn Gott gefallen erzwungene, unwillige Dienste nicht, und er will sie auch nicht haben, wie Sankt Paulus 2. Korinther 9 sagt: ‚Gott hat einen fröhlichen Geber lieb‘; ohne Zweifel ist er umgekehrt einem unfröhlichen, unwilligen Geber feind. Daher will auch Sankt Paulus die edle Jungfräulichkeit nicht, wo sie erzwungen und unwillig geschieht, 1. Korinther 7. Solche fröhliche Lust zum Gottesdienst aber gibt weder Kloster noch Kappe, weder Gelübde noch Werk, sondern allein der Heilige Geist.\n\nWie viele, meinst du aber, sind Nonnen in Klöstern, wo das tägliche Wort Gottes nicht geht, die fröhlich und mit Lust, ungezwungen ihren Gottesdienst tun und den Orden tragen? Freilich unter tausend kaum eine. Was ist es dann, dass du ein solches Kind so sein Leben und alle seine Werke verlieren und dazu die Hölle damit verdienen lässt? Wäre es nicht besser, wenn sie schon etwas ungern und mit Unlust tun soll, sie wäre verheiratet und täte solche Mühe und Unlust im Ehestand äußerlich gegenüber den Menschen, ihrem Mann, Kind, Gesinde und Nachbarn usw.? Weil also Gott kein Dienst gefällt, er geschehe denn willig von Herzen und mit Lust, so folgt, dass auch kein Gelübde weiter gelten, geschehen oder gehalten werden soll, als die Liebe und Lust da ist, das heißt, als der Heilige Geist da ist. Darum: Weil ein solches Gelübde ohne Lust und Geist geschieht, achtet Gott es nicht und nimmt es nicht an. So ist auch dies ein hinreichender Grund, Gelübde und Kloster zu lassen und jedermann in einen anderen Stand herauszuhelfen.",
         note="‚Unter tausend kaum eine‘ ist eine Schätzung ohne Grundlage, eine polemische Zahl. Das Argument selbst, dass Gott keinen erzwungenen Dienst will, benutzte der Nürnberger Konvent in umgekehrter Richtung: ‚Jeder Geist will frei und ungezwungen sein‘, darum solle man den Schwestern keine Prediger aufzwingen (Modul ‚Die große Sündflut‘, Bittschrift [3]). Melanchthon war es im November 1525 ‚sehr zuwider, dass man die Leute mit Gewalt nötigt‘ (Modul ‚Melanchthon im Beichthaus‘, Besuch [3])."),
    dict(n=7, titel="‚Nicht geschaffen, Jungfrau zu sein‘; das Gelübde", pg="WA 11, S. 398–399", lang="fnhd",
         orig="Auffs vierde, Wie wol man sich dißer ursach schier schemen mus, so ists doch fast der grossisten eyne, kloster und kappen zu lassen: Nemlich das unmuglich ist, die gabe der keuschheyt so gemeyne sey als die kloster sind. Denn eyn weybs bild ist nicht geschaffen, jungfraw zu seyn, sondern kinder zu tragen wie Gen. 1. Gott sprach nicht alleyne zu Adam, sondern auch zu Heva ‚seyt fruchtbar und mehret euch‘ [...] Und solchs ist nicht zu eynem weyb noch zu zweyen, sondern zu allen gesagt und keyne ausgeschlossen, Got zihe sie denn selber aus nicht durch unser gelubd odder freyen willen, sondern durch seynen eygen radt und willen mechtiglich. Wo er das nicht thutt, soll ein weybs bild ein weyb bleyben, frucht tragen, datzu es gott geschaffen hat, und nicht besser machen denn ers gemacht hatt. [...]\n\nHie thun sie denn zwo eynrede. Die erst: Man solle die gelubd hallten. Das ist warlich war, wenn du gottlich gelobist, das deyn ist und ynn deyner macht steht. Ich horet hie zu eyn gelerten man eyn mal sagen: Meyn mutter hatt gelobt, Ich sollt eyn bischoff werden, Wie soll ichs hallten? Deyn ists aber nicht jungfraw seyn widder eyngesetzte natur, Sondern wie S. Paulus sagt 1. Corin. 7: Es ist eyn gottis gabe. Wie ich nu keyn Gottis gabe kan geloben, ßo kan ich auch keuschheyt nicht geloben. Es mus alles zuvor meyn seyn, ehe ichs gelobe. [...] Und ist dis exempel woll zu mercken, das nicht gnug ist gesagt: ja ich habs gelobt, ich mus hallten. Lieber, sihe zuvor, obs muglich und gotlich ist, was du gelobest, sonst wenn unmuglich gelubd gulde, mochtestu wol geloben eyn mutter gottis werden wie Maria.",
         en="Viertens: Obwohl man sich dieses Grundes beinahe schämen muss, ist er doch fast einer der größten, Kloster und Kappe zu lassen: nämlich dass es unmöglich ist, dass die Gabe der Keuschheit so verbreitet sei, wie es die Klöster sind. Denn eine Frau ist nicht geschaffen, Jungfrau zu sein, sondern Kinder zu tragen, wie Genesis 1. Gott sprach nicht allein zu Adam, sondern auch zu Eva: ‚Seid fruchtbar und mehret euch‘ [...] Und das ist nicht zu einer Frau oder zu zweien gesagt, sondern zu allen, und keine ist ausgeschlossen, Gott nehme sie denn selbst aus, nicht durch unser Gelübde oder unseren freien Willen, sondern mächtig durch seinen eigenen Rat und Willen. Wo er das nicht tut, soll eine Frau eine Frau bleiben, Frucht tragen, wozu Gott sie geschaffen hat, und es nicht besser machen, als er es gemacht hat. [...]\n\nHier erheben sie nun zwei Einwände. Der erste: Man solle die Gelübde halten. Das ist wahrlich wahr, wenn du etwas Göttliches gelobst, das dein ist und in deiner Macht steht. Ich hörte hier einmal einen gelehrten Mann sagen: Meine Mutter hat gelobt, ich sollte Bischof werden; wie soll ich das halten? Es steht aber nicht bei dir, gegen die eingesetzte Natur Jungfrau zu sein, sondern es ist, wie Sankt Paulus 1. Korinther 7 sagt, eine Gabe Gottes. Wie ich nun keine Gabe Gottes geloben kann, so kann ich auch Keuschheit nicht geloben. Es muss alles zuvor mein sein, ehe ich es gelobe. [...] Und dieses Beispiel ist wohl zu merken, dass es nicht genug ist zu sagen: Ja, ich habe es gelobt, ich muss es halten. Lieber, sieh zuvor, ob es möglich und göttlich ist, was du gelobst; sonst, wenn ein unmögliches Gelübde gälte, könntest du wohl auch geloben, eine Mutter Gottes zu werden wie Maria.",
         note="Hier steht Luthers Frauenbild ohne Umschweife: Eine Frau sei zum Kindertragen geschaffen, die Ausnahme mache allein Gott. Der Satz gehört zur Sache und wird nicht geglättet. Ausgelassen sind die biblischen Belege (Eva, Samuels Mutter, Sauls Schwur) und ein Abschnitt über die Keuschheit des Hieronymus (S. 399, Z. 6–36). Die Gegenposition zum Gelübde steht bei Caritas 1525: ‚Keine Schwester hat mir oder einem lebenden Menschen etwas gelobt, sondern Gott dem Allmächtigen‘ (Modul ‚Die Väter genommen‘, Artikel [2]), und im Beichthaus mit Melanchthon: einig in allem, ‚nur wegen der Gelübde‘ nicht (Modul ‚Melanchthon im Beichthaus‘, Besuch [3])."),
    dict(n=8, titel="Die neun Namen; ‚die laß man bleiben‘", pg="WA 11, S. 400", lang="fnhd",
         orig="Die Ander eynrede ist, das es ergerlich sey, widder den gemeynen allten brauch und lere, und der schwachen gewissen sei zu schonen. Antwortt: Ergernis hyn, Ergernis her. Nott bricht eyßen und hatt keyn ergernis. Ich soll der schwachen gewissen schonen, ßo fern es on fahr meyner seelen geschehen mag. Wo nicht, ßo soll ich meyner seelen radten, es erger sich dran die gantze odder halbe wellt. [...]\n\nDas will ich auff diß mall, meyn gutter freund, kurtzlich zur verantworttung gegeben haben fur euch, fur mich und fur diße jungfrawen, auch fur alle, die dißem exempel wollen nach folgen [...]\n\nIch will aber auch die jungfrawen hye nennen, auff das alles ja frey am tage sey. Und sind nemlich dyße: Magdalena Staupitzyn, Elisabeth Canitzyn, Vronica Zesschaw, Margaretha Zesschaw, yhr schwester, Laneta von Golis, Ave Grossyn, Katherina von Bore, Ave von Schonfelt, Margaretha von Schonfeldt, yhr schwester. Der almechtig Gott wollt gnediglichen erleuchten alle freunde der ihenygen, ßo mit far und unlust ynn klostern sind, das sie yhn trewlich eraus helffen. Wilche aber geyst verstendig sind und klosterey nutzlich wissen zu brauchen und gerne drynnen sind, die laßz man bleyben ym namen Gottis.\n\nHie mit befelh ich euch Gott, und grust mir ewr liebe Audi und alle freunde ynn Christo. Gegeben zu Wittemberg am Freytag ynn der osterwoche. Anno. 1523.",
         en="Der andere Einwand ist, es sei ärgerlich, gegen den allgemeinen alten Brauch und die alte Lehre, und man müsse die schwachen Gewissen schonen. Antwort: Ärgernis hin, Ärgernis her. Not bricht Eisen und kennt kein Ärgernis. Ich soll die schwachen Gewissen schonen, soweit es ohne Gefahr für meine Seele geschehen kann. Wo nicht, so soll ich für meine Seele sorgen, mag sich daran die ganze oder die halbe Welt ärgern. [...]\n\nDas will ich diesmal, mein guter Freund, kurz zur Verantwortung gegeben haben, für Euch, für mich und für diese Jungfrauen, auch für alle, die diesem Beispiel folgen wollen [...]\n\nIch will aber auch die Jungfrauen hier nennen, damit alles offen am Tag sei. Es sind nämlich diese: Magdalena von Staupitz, Elisabeth von Canitz, Veronika von Zeschau, Margaretha von Zeschau, ihre Schwester, Laneta von Gohlis, Ave Gross, Katharina von Bora, Ave von Schönfeld, Margaretha von Schönfeld, ihre Schwester. Der allmächtige Gott wolle gnädig alle Verwandten derer erleuchten, die mit Gefahr und Unlust in Klöstern sind, dass sie ihnen treulich heraushelfen. Welche aber geistlich verständig sind, das Klosterwesen nützlich zu gebrauchen wissen und gern darin sind, die lasse man bleiben im Namen Gottes.\n\nHiermit befehle ich Euch Gott, und grüßt mir Eure liebe Audi und alle Freunde in Christus. Gegeben zu Wittenberg am Freitag in der Osterwoche, im Jahr 1523.",
         note="Freitag in der Osterwoche 1523: Ostern fiel auf den 5. April, also der 10. April; so datiert auch die Weimarer Ausgabe (S. 388). Die Namen sind in Luthers Schreibung wiedergegeben, die Übersetzung gibt die heute übliche Form; Katharina von Bora heiratete 1525 Luther, und Koppe wurde zur Hochzeit eingeladen. ‚Audi‘ grüßt Luther nach der Anmerkung der Weimarer Ausgabe auch in zwei späteren Briefen an Koppe; wer gemeint ist, sagt die Ausgabe nicht. Der vorletzte Satz ist für dieses Modul der wichtigste: Wer gern im Kloster ist, die lasse man bleiben. Die Nürnberger Schwestern verlangten 1524 bis 1528 nichts anderes (Modul ‚Die große Sündflut‘, Bittschrift [5])."),
]

GEORG = [
    dict(n=1, titel="‚Was grausamer Aufruhr … aus dem lutherischen Evangelium‘", pg="Höfler S. LXII–LXIV", lang="fnhd",
         orig="Instruktion für den Reichstag zu Augsburg vergangen Martini in Augsburg, dann auf den ersten Tag des Monats Mai gegen Speier. Otto Packen gegeben 1526. [...]\n\n„Es ist uffenbar am tag was grausamer aufrur in unnsern landen entstanden auß dem lutherischen evangelio den der allmechtige goth durch sein gotlich Gnad vermittelst unser person vnd unserem heren und frund auch vnnser getrewen underthanen hilff gewendt, wo das nicht gescheen so were zu besorgen vnnsere lannd sampt anderen lendern so umb unns liegen musten ytzt dem lutterischen Evangelio vnterwurffen und also von dem gehorsam cristenl. Kirchen abgesondert, darzu alle von goth eingesatzte oberkeiten sampt allen prelaten und adel verdrukt, erworget vnd vertriben seyn, das solchs gots auß gnaden durch vnns geworgkt, ist vnns bey denselben dem lutterischen Evangelio anhengigk nicht zu kleinem nachteyl, schimpff, verkleynerung unnser Ehren und gelympffe gereicht vnd trachten noch stetts wie sie vnns vnd die vnnsern auch andere, so ynen nicht anhengkik zufellig machen mochten, meher mit argem, denn mit gutem, meher mit gewalt und besser mauterey (böser Meuterei) denn mit recht oder billigkeyt. So kompt vns teglich fur und sy selber nicht schweigen konnen sonder drawen vnnd lassen schrifft außgehen, das vor der hant sey, das kein furst noch bischoff seyn, sunder mussen alle in kurz in drummern gehen, als hat vnns auch lutter selbst zugeschrieben wen wir seyner lehre nicht anhängig, das uns nicht woll gelyngen mochte [...]",
         en="Instruktion für den Reichstag, der auf Martini [1525] nach Augsburg und dann auf den ersten Mai nach Speyer ausgeschrieben war, Otto Pack gegeben 1526. [...]\n\n„Es ist offenbar am Tag, was für ein grausamer Aufruhr in unseren Landen aus dem lutherischen Evangelium entstanden ist, den der allmächtige Gott durch seine göttliche Gnade mittels unserer Person, unseres Herrn und Freundes und der Hilfe unserer getreuen Untertanen abgewendet hat. Wäre das nicht geschehen, so wäre zu befürchten, dass unsere Lande samt anderen Ländern um uns jetzt dem lutherischen Evangelium unterworfen und so vom Gehorsam der christlichen Kirche abgesondert sein müssten, dazu alle von Gott eingesetzten Obrigkeiten samt allen Prälaten und dem Adel unterdrückt, erwürgt und vertrieben. Dass Gott dies aus Gnade durch uns gewirkt hat, hat uns bei denen, die dem lutherischen Evangelium anhängen, zu nicht geringem Nachteil, Schimpf und Verkleinerung unserer Ehre und unseres Ansehens gereicht, und sie trachten noch ständig, wie sie uns und die Unseren und auch andere, die ihnen nicht anhängen, zu Fall bringen könnten, mehr mit Argem als mit Gutem, mehr mit Gewalt und böser Meuterei als mit Recht oder Billigkeit. So kommt uns täglich zu Ohren, und sie selbst können es nicht verschweigen, sondern drohen und lassen Schriften ausgehen, es stehe bevor, dass es keinen Fürsten und keinen Bischof mehr gebe, sondern alle müssten in Kürze in Trümmer gehen; so hat uns auch Luther selbst geschrieben, wenn wir seiner Lehre nicht anhingen, möchte es uns nicht wohl gelingen [...]",
         note="Herzog Georg von Sachsen, katholischer Fürst und Luthers ‚Widersacher‘, wie ihn die Weimarer Ausgabe nennt, an seinen Rat Otto Pack. Der ‚grausame Aufruhr‘ ist der Bauernkrieg von 1525; der Text nennt Müntzer selbst (‚widder den munzer und widder den Lutter streben‘). Dass die Niederschlagung, an der Georg nach der neueren Literatur bei Frankenhausen beteiligt war, Tausende Tote kostete, sagt die Instruktion nicht: Sie rühmt nur, dass Gott den Aufruhr ‚durch uns‘ abgewendet habe. Höfler druckt den Anfang als Fußnote (S. LXII–LXIII), den Rest im Text; seine Vorlage nennt er an dieser Stelle nicht, eine Prüfung am Original war nicht möglich. Die Klammern ‚(böser Meuterei)‘ sind Höflers Erklärungen. Die Instruktion ist in Höflers eigener Schreibung wiedergegeben, die zwischen u und v, ü und u schwankt."),
    dict(n=2, titel="‚Die kauft man mit Geld heraus‘", pg="Höfler S. LXIV–LXV", lang="fnhd",
         orig="„Wie man nun von den artikeln im ausschreiben vermeldt solt reden oder sonst vorfallen wurde das man sagen wollt, man wußte von berurter anzeygung nichts sonderlichs, es were auch so böse nicht als mans machte und wolte also clerlichere anzeigung haben, so sol unser Geschikter vorlegen das Büchlein, so Lutther hat nehst lassen außgehen vnd anzeigen, das tegelich lesterbrieff vnd buchlein hyn und wyder gedrukt, das lutterisch evangelium zu underhalten vnd die jhenen so den gehorsam der cristlichen kirchen zu vorhalten gedenken, geschmeht werden. Es unterbleipet auch nicht, sonnder wyrdt tegelich gearbayt die geistlichen mans und weybs personen aus den clostern mit yren predigen zu bewegen mit draw (Androhung) ewiger pein der hellen (Hölle) mit vorheyschung fleischlicher und ewiger wollust nnd selikeit. So sie also aus den clostern entlauffen, werden sie in umbligenden furstenthumben uffgehalten und gestergkt, als hetten sie recht und wol gethan, dyjhenen so yhn heraushelffen, dungken sich gerumet, so es doch beym leben im rechten verboten ist, vnnd das meher ist, welche man nicht mit predigen oder buchern aus dem closter brengen kann, die kaufft man mit gelde heraus und wo man sie myt gelde nicht gewynnen kann, so leget man soviel gewalts und unrechts an sy, das sy heraus mussen vnnd diese heren dye sie also mit lysten oder gewalt herauß bracht haben, die gebrauchen denn der guter als were es recht wol ererbtes guth, Darauß clerlich erscheynet das jhne meher gelibet ihre guther zu gebrauchen, denn das sie wolten fromme erliche gottsdiener und dienerinen haben, das alles wissen wyr anzuzeygen dermossen das es unlaugkenbar ist.“",
         en="„Wenn man nun von den Artikeln reden soll, die im Ausschreiben genannt sind, oder wenn sonst vorgebracht würde, man wisse von dem erwähnten Vorwurf nichts Besonderes, es sei auch nicht so schlimm, wie man es mache, und man wolle deutlichere Belege haben, so soll unser Gesandter das Büchlein vorlegen, das Luther neulich hat ausgehen lassen, und zeigen, dass täglich Schmähbriefe und Büchlein hin und wider gedruckt werden, um das lutherische Evangelium zu stützen, und dass die geschmäht werden, die den Gehorsam der christlichen Kirche zu halten gedenken. Es unterbleibt auch nicht, sondern es wird täglich daran gearbeitet, die geistlichen Männer und Frauen mit ihren Predigten aus den Klöstern zu bewegen, mit Androhung ewiger Pein der Hölle und mit Verheißung fleischlicher und ewiger Wollust und Seligkeit. Wenn sie so aus den Klöstern entlaufen, werden sie in den umliegenden Fürstentümern aufgenommen und bestärkt, als hätten sie recht und gut getan; die ihnen heraushelfen, rühmen sich dessen, obwohl es im Recht bei Leib und Leben verboten ist. Und was mehr ist: Welche man nicht mit Predigen oder Büchern aus dem Kloster bringen kann, die kauft man mit Geld heraus, und wo man sie mit Geld nicht gewinnen kann, legt man so viel Gewalt und Unrecht an sie, dass sie heraus müssen; und diese Herren, die sie so mit List oder Gewalt herausgebracht haben, gebrauchen dann die Güter, als wäre es recht und wohl ererbtes Gut. Daraus erscheint klar, dass ihnen mehr daran liegt, die Güter zu gebrauchen, als fromme, ehrliche Gottesdiener und Dienerinnen zu haben. Das alles wissen wir so zu belegen, dass es unleugbar ist.“",
         note="‚In umliegenden Fürstentümern aufgehalten und gestärkt‘: so wie die Nonnen aus Nimbschen, die nach Wittenberg in Kursachsen kamen, weil ihre Familien Georgs Rache fürchteten (Ursach [1]). Welches ‚Büchlein‘ Luthers gemeint ist, sagt die Instruktion nicht. Georgs Vorwurf ist parteiisch, aber er nennt, was die Nürnberger Quellen von der anderen Seite zeigen: Gewalt beim Herausholen (Modul ‚Da stee ich‘) und Streit ums Geld (Anna Schwarz' hundert Gulden, Modul ‚Visitiert und verlassen‘, Anna [4]; das Kostgeld der drei Töchter, ‚Da stee ich‘, Danach [2]). Höfler setzt dazu die Fußnote: ‚Damit möge man vergleichen, was in den Briefen der Charitas folgt.‘ ‚(Androhung)‘ und ‚(Hölle)‘ sind Höflers Erklärungen."),
]

doc = {
    "id": "vergleich",
    "titel": "Luther und die Nonnen, 1523 und 1526",
    "autor": "Martin Luther; Herzog Georg von Sachsen",
    "jahr": "1523–1526",
    "sprache": "de",
    "orig_sprache": "fnhd",
    "pg_label": "",
    "quelle": "M. Luther, Ursach und Antwort, daß Jungfrauen Klöster göttlich verlassen mögen (Wittenberg 1523), in: D. Martin Luthers Werke. Kritische Gesamtausgabe, Bd. 11 (Weimar: Böhlau 1900), S. 387–400 (Internet Archive: werkekritischege11luthuoft); Herzog Georg von Sachsen, Instruktion für Otto Pack (1526), nach C. Höfler (Hg.), Denkwürdigkeiten der Charitas Pirkheimer (Bamberg 1852), Einleitung S. LXII–LXV (Internet Archive: 11420769bsb). Übersetzung: eigene Arbeitsübersetzung.",
    "hinweis": "Luthers Text nach der Weimarer Ausgabe am Seitenbild gelesen (die Texterkennung des Fraktursatzes ist unbrauchbar), in deren Schreibung des Erstdrucks; das ſʒ des Satzes ist als ß wiedergegeben, Lesarten und Randnotizen der Ausgabe sind weggelassen. Herzog Georgs Instruktion nach Höflers Abdruck, am Seitenbild gelesen; Höfler nennt seine Vorlage an dieser Stelle nicht. Auslassungen sind mit [...] bezeichnet. Ein direkter Bezug zwischen Luther und dem Nürnberger Klarakloster ist in den hier benutzten Quellen nicht belegt: Das Modul stellt gegenüber, es behauptet keine Verbindung.",
    "sections": [
        {"id": "ursach", "autor": "Martin Luther", "titel": "Ursach und Antwort, April 1523", "zk": "Ursach",
         "plates": ["bora1526", "wa_s394", "wa_s400"],
         "viz": "wollen",
         "blurb": "Am Samstag vor Ostern 1523 verlassen zwölf Zisterzienserinnen das Kloster Nimbschen, neun kommen nach Wittenberg, unter ihnen Katharina von Bora. Luther rechtfertigt die Flucht in einem offenen Brief an den Helfer: Die Frauen hätten ihre Eltern vergeblich gebeten, im Kloster fehle Gottes Wort, Gott wolle keinen erzwungenen Dienst, eine Frau sei nicht geschaffen, Jungfrau zu sein. Und am Schluss: Wer gern im Kloster ist, ‚die laß man bleiben im Namen Gottes‘.",
         "units": URSACH},
        {"id": "georg", "autor": "Herzog Georg von Sachsen", "titel": "Herzog Georg: die andere Seite, 1526", "zk": "Herzog Georg",
         "plates": ["georg_cranach", "hoefler_lxv"],
         "blurb": "Herzog Georg von Sachsen, dessen Rache die Familien der Nonnen von Nimbschen nach der Weimarer Ausgabe fürchteten, instruiert 1526 seinen Gesandten zum Reichstag: Man predige die Ordensleute mit Höllendrohung und Wollust aus den Klöstern; wen man so nicht herausbringe, den kaufe man mit Geld heraus, und wo das nicht reiche, lege man ‚so viel Gewalt und Unrecht an sie, dass sie heraus müssen‘; die Herren nähmen dann die Güter. Höfler druckte die Instruktion 1852 in seiner Einleitung zu Caritas' Denkwürdigkeiten ab, mit der Bitte, sie mit deren Briefen zu vergleichen.",
         "units": GEORG},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("vergleich.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
